/**
 * src/shared/contracts-galaxy.ts — cross-sub-task contract types for the
 * deep-sky navigable profile galaxy ("Sky Roads", /profile "Your Sky").
 *
 * Owned by brainiac (arch task t_2156deb1). Build sub-task workers (steel)
 * IMPORT from here. DO NOT EDIT this file directly — if a contract is wrong,
 * the arch task must be re-opened.
 *
 * Domain: kara's approved "Sky Roads" concept (t_ea789325) — the LOD galaxy
 * (ONE focused constellation at full deep-sky fidelity + compact glyph nodes
 * for every other course), the guided Sky Road (traveled/untraveled segments
 * threading the sectors in journey order), the pulsing cyan Frontier Waypoint
 * (the "next" beacon), the dolly-and-tilt CameraRig flight controller, and
 * the HUD chrome (SkyChart, ConstellationCard, JourneyRail, RankChip, Legend).
 *
 * FILE PLACEMENT (ADR-308): the task brief said "compile as
 * src/shared/contracts.ts", but that file is already owned by the quiz-tier
 * arch (t_cf2e9661) and is documented "DO NOT EDIT this file directly". To
 * avoid a collision hotspot and follow the existing domain-suffixed convention
 * (contracts-constellations.ts, contracts-course-catalog.ts, contracts-account.ts),
 * the galaxy contracts live in this dedicated file. Steel imports from here.
 *
 * Pure-model rule (ADR-305): the new model types (GlyphStar, SkyRoad,
 * GalaxySectorNav, frontierSlug) are implemented in the SSR-safe, unit-tested
 * galaxy-model.ts. This file is the interface contract; the model file is the
 * implementation. No three/r3f imports anywhere in this file.
 */

import type { SpectralClass } from "@/components/Constellations/3d/star-model";
import type {
  GalaxySector,
  ArticleStar,
  SectorState,
} from "@/components/Constellations/3d/galaxy-model";
import type { RankId } from "@/shared/contracts-constellations";

/* ------------------------------------------------------------------ */
/*  Pure model layer — galaxy-model.ts extension (sub-task 1)          */
/* ------------------------------------------------------------------ */

/**
 * The bright-anchor subset of a real asterism (apparent magnitude < 3.5) that
 * forms the recognizable figure at distance. This is what a "constellation
 * glyph" node renders — the same set `projectAsterism` uses to frame the
 * figure (Orion's hourglass, Cassiopeia's W). Fainter members only materialize
 * when the camera approaches (LOD). Astronomically honest: the bright anchors
 * ARE what make a constellation recognizable.
 */
export interface GlyphStar {
  /** Bayer designation / catalogue name (e.g. "Betelgeuse (α Ori)"). */
  name: string;
  /** World position (projected from the real asterism, deterministic). */
  position: [number, number, number];
  /** Real spectral class (OBAFGKM) — drives the glyph star's color. */
  spectralClass: SpectralClass;
  /** Real apparent magnitude (lower = brighter). */
  magnitude: number;
  /** True for astronomically-red members (Betelgeuse) — ADR-303 accent. */
  isRedGiantAccent?: boolean;
  /** True for a nebula anchor (M42). */
  isNebula?: boolean;
}

/**
 * A galaxy sector extended for the navigable galaxy. `glyph` is the LOD
 * bright-anchor subset; `focus` marks the sector currently rendered at full
 * deep-sky fidelity (the one the camera is at / selected). Steel adds these
 * two fields to the existing `GalaxySector` in galaxy-model.ts.
 */
export interface GalaxySectorNav extends GalaxySector {
  /** The recognizable bright-anchor figure for the LOD glyph node. */
  glyph: GlyphStar[];
  /** True when this sector is the focused constellation (full fidelity). */
  focus: boolean;
}

/**
 * The guided "Sky Road" — the route line threading the sectors in recommended
 * learning order (the course dependency flow / authored journey order, falling
 * back to the existing ring order). Traveled segments (behind you) render warm
 * golden; untraveled (ahead) render faint cool dashed.
 */
export interface SkyRoad {
  /** seriesSlugs in journey order (the road's node sequence). */
  nodes: string[];
  /** seriesSlugs behind you (completed / certified) — warm gold segments. */
  traveled: string[];
  /** seriesSlugs ahead (unstarted / in-progress) — faint cool segments. */
  untraveled: string[];
  /** Catmull-Rom curve through the node world positions (the drawn path). */
  curve: [number, number, number][];
}

/**
 * The next recommended sector — the first unstarted/in-progress sector with
 * availability, in road order. Pure, deterministic. Returns null when every
 * sector is complete (no frontier).
 */
export type FrontierSlug = (
  sectors: GalaxySectorNav[],
  road: SkyRoad,
) => string | null;

/** The full pure-model output of `buildGalaxyModel` (extended). */
export interface GalaxyModel {
  sectors: GalaxySectorNav[];
  articles: ArticleStar[];
  road: SkyRoad;
  /** The next waypoint slug (null when the whole sky is lit). */
  frontierSlug: string | null;
}

/* ------------------------------------------------------------------ */
/*  Navigation state (shared by scene + HUD)                           */
/* ------------------------------------------------------------------ */

/** Camera flight mode for the dolly-and-tilt rig. */
export type CameraMode = "overview" | "flying" | "settled";

/** The galaxy's navigation state — the single source the scene + HUD read. */
export interface GalaxyNavigationState {
  /** Focused sector slug (null = overview / no selection). */
  focusSlug: string | null;
  /** The next waypoint slug (pulsing cyan reticle). */
  frontierSlug: string | null;
  /** Current camera flight mode. */
  cameraMode: CameraMode;
}

/* ------------------------------------------------------------------ */
/*  Scene layer — ProfileScene rewrite (sub-task 2)                    */
/* ------------------------------------------------------------------ */

/** LOD glyph node — a compact bright-anchor asterism at --glyph-scale. */
export interface ConstellationGlyphProps {
  sector: GalaxySectorNav;
  /** True when this node carries the pulsing Frontier Waypoint. */
  isFrontier: boolean;
  /** Click → fly to this sector. */
  onSelect: (seriesSlug: string) => void;
  prefersReducedMotion?: boolean;
}

/** The additive route line through the node positions. */
export interface SkyRoadProps {
  road: SkyRoad;
  sectors: GalaxySectorNav[];
  prefersReducedMotion?: boolean;
}

/** The pulsing cyan reticle ring + "NEXT · [course]" tag on the frontier. */
export interface WaypointReticleProps {
  sector: GalaxySectorNav;
  prefersReducedMotion?: boolean;
}

/**
 * Dolly-and-tilt flight controller. Overview = sky-chart altitude with slow
 * Keplerian drift + pointer parallax; fly = 3-phase (pull back, arc toward
 * target with damped easing, decelerate + FOV breath). Reduced motion =
 * static settled overview (selecting swaps focus, no flight).
 */
export interface CameraRigProps {
  focusSlug: string | null;
  sectors: GalaxySectorNav[];
  frontierSlug: string | null;
  prefersReducedMotion?: boolean;
  /** Fired when a flight settles on a sector (or null on return to overview). */
  onSettled?: (slug: string | null) => void;
}

/* ------------------------------------------------------------------ */
/*  HUD layer — 2D DOM overlays (sub-task 3)                           */
/* ------------------------------------------------------------------ */

/** SkyChart — upgraded minimap: node dots on the route, traveled/untraveled
 *  road, "you are here" pulse, next-waypoint marker, view cone. Click → fly. */
export interface SkyChartProps {
  sectors: GalaxySectorNav[];
  road: SkyRoad;
  focusSlug: string | null;
  frontierSlug: string | null;
  onSelect: (seriesSlug: string) => void;
}

/** ConstellationCard — contextual info card (replaces the tooltip-only
 *  affordance): name, course, state chip, lit/total, "Continue / Next star". */
export interface ConstellationCardProps {
  sector: GalaxySectorNav;
  /** "Continue / Next star" CTA (navigates into the focused course). */
  onContinue?: () => void;
}

/** JourneyRail — horizontal waypoint strip of course names in road order,
 *  state-coded, frontier highlighted, prev/next arrows. */
export interface JourneyRailProps {
  sectors: GalaxySectorNav[];
  road: SkyRoad;
  focusSlug: string | null;
  frontierSlug: string | null;
  onSelect: (seriesSlug: string) => void;
}

/** RankChip — "EXPLORER · 55% lit" (the Monitor aggregate). */
export interface RankChipProps {
  rank: RankId;
  /** 0-100 fraction of the galaxy lit (rank → illumination). */
  illuminationPct: number;
}

/** Legend — collapsible state key (unstarted / in-progress / completed /
 *  certified / next). */
export interface LegendProps {
  open?: boolean;
}

/* ------------------------------------------------------------------ */
/*  Achievement state (unchanged, re-exported for the HUD)             */
/* ------------------------------------------------------------------ */

/** Re-export the sector achievement ladder so HUD components share one type. */
export type { SectorState };
