/**
 * src/shared/contracts-course-catalog.ts — cross-sub-task contract types for the
 * course-catalog + entitlements + admin build.
 *
 * Owned by brainiac (arch task t_22b26cb9). Sub-task workers (steel A–E)
 * IMPORT from here. DO NOT EDIT this file directly — if a contract is wrong,
 * reopen the arch task.
 *
 * Mirrors: docs/system-architecture-course-catalog-admin.html (t_22b26cb9)
 * DB source of truth: supabase/migrations/008_course_catalog.sql
 */

/* ------------------------------------------------------------------ */
/*  Core enums (mirror DB CHECK constraints in migration 008)          */
/* ------------------------------------------------------------------ */

/** Course lifecycle state — lives in `courses.status`, NOT content files. */
export type CourseStatus = "pending" | "live" | "archived";

/** How a course is gated. Lives in `courses.access_model`. */
export type AccessModel =
  | "free"
  | "subscription"
  | "one-time"
  | "sub-or-one-time"
  | "granted";

/** How an entitlement was granted — source of truth in `user_entitlements.source`. */
export type EntitlementSource = "granted" | "one-time";

/** Role stored in `user_roles.role` (default member). */
export type UserRole = "admin" | "member";

/* ------------------------------------------------------------------ */
/*  DB row shapes (snake_case — mirror migration 008 columns)          */
/* ------------------------------------------------------------------ */

/** `courses` row — keyed by series_slug. Platform fields only; content stays in files. */
export interface CourseRow {
  id: string;
  series_slug: string;
  title: string;
  status: CourseStatus;
  access_model: AccessModel;
  /** Price in cents; NULL for free/granted/read-only. Display + future Stripe. */
  price_cents: number | null;
  launched_at: string | null;
  created_at: string;
  updated_at: string;
}

/** `user_roles` row. */
export interface UserRoleRow {
  user_id: string;
  role: UserRole;
  updated_at: string;
}

/** `user_entitlements` row. revoked_at NULL = active. */
export interface UserEntitlementRow {
  id: string;
  user_id: string;
  course_id: string;
  source: EntitlementSource;
  grant_note: string | null;
  granted_by: string | null;
  granted_at: string;
  revoked_at: string | null;
}

/** `subscriptions` row — read-only display this build; nothing writes it except schema. */
export interface SubscriptionRow {
  id: string;
  user_id: string;
  plan: string;
  status: "active" | "trialing" | "canceled" | "past_due";
  current_period_end: string | null;
  created_at: string;
}

/** `admin_audit_log` row — read-only in the panel; every admin action writes one. */
export interface AdminAuditLogRow {
  id: number;
  actor_user_id: string | null;
  action: string;
  target_type: string;
  target_id: string | null;
  details: Record<string, unknown> | null;
  created_at: string;
}

/* ------------------------------------------------------------------ */
/*  src/lib/access.ts — the server-side access seam                    */
/* ------------------------------------------------------------------ */

/** Signed-in user's id; null for guests. */
export type UserId = string | null;

/** What a single course means to the current user on a catalog surface. */
export interface CatalogCourseEntry {
  course: CourseRow;
  /** Status-driven visibility: live (all), pending/archived (admin only). */
  visible: boolean;
  /** Model + entitlement-driven: may the user read gated content? */
  canAccess: boolean;
}

/** Full catalog the current user may see + their access per course. */
export interface CatalogForUserResult {
  entries: CatalogCourseEntry[];
  /** True when the caller is an admin (sees pending/archived). */
  isAdmin: boolean;
}

/** Access decision for a single course on a content surface (lesson/check/exam/cert/API). */
export type CourseAccessDecision =
  /** Course not live / no courses row → treat as not launched. */
  | { kind: "not-launched" }
  /** Admin previewing a pending/archived course → content renders. */
  | { kind: "admin-preview" }
  /** User may read gated content. */
  | { kind: "granted" }
  /** User must see the paywall (live + not entitled). */
  | { kind: "paywall" };

/** Access seam API surface — the single decision function every surface calls. */
export interface AccessSeam {
  /** Catalog for a surface: visible courses + per-course access. */
  getCatalogForUser: (userId: UserId) => Promise<CatalogForUserResult>;
  /** Single-course decision for a content surface. */
  decideCourseAccess: (
    userId: UserId,
    seriesSlug: string,
  ) => Promise<CourseAccessDecision>;
  /** Role check for /admin gating. */
  isAdmin: (userId: UserId) => Promise<boolean>;
}

/* ------------------------------------------------------------------ */
/*  Catalog + gating sweep — page/route contracts                      */
/* ------------------------------------------------------------------ */

/** Course row joined with content-derived display fields for catalog cards. */
export interface CatalogCourseView {
  course: CourseRow;
  /** Display name from series.json; fallback: humanized series_slug. */
  name: string;
  /** Description from series.json; fallback: "". */
  description: string;
  gradient: string;
  /** Published lesson count (from build data). */
  lessonCount: number;
  totalLessons: number;
  /** User's access on this card (drives lock vs click-through). */
  canAccess: boolean;
}

/** Input contract for the gating sweep — same shape across lesson/check/exam/cert pages. */
export interface GatedContentPageProps {
  seriesSlug: string;
  lessonSlug?: string;
}

/** Canonical lesson slugs for a series (published only — pending excluded). */
export interface SeriesLessonSlugs {
  seriesSlug: string;
  lessonSlugs: string[];
}

/* ------------------------------------------------------------------ */
/*  Admin API contracts                                               */
/* ------------------------------------------------------------------ */

/** Admin course mutation body (US-009). */
export interface AdminCourseUpdateRequest {
  status?: CourseStatus;
  access_model?: AccessModel;
  price_cents?: number | null;
}

/** Admin course list row (US-009/014) — course + entitlement summary. */
export interface AdminCourseListRow {
  course: CourseRow;
  /** Number of active (non-revoked) granted/one-time entitlements. */
  activeEntitlementCount: number;
}

/** Admin user list row (US-010) — role + entitlements for the matrix. */
export interface AdminUserListRow {
  user_id: string;
  email: string;
  display_name: string | null;
  role: UserRole;
  /** Active entitlements keyed by course_id → source. */
  entitlements: Record<string, EntitlementSource>;
}

/** Grant/revoke request (US-012). */
export interface GrantEntitlementRequest {
  userId: string;
  courseId: string;
  note?: string;
}

/** Bulk grant request (US-013). */
export interface BulkGrantRequest {
  userIds: string[];
  courseId: string;
  note?: string;
}

/** Role assignment request (US-011). */
export interface SetRoleRequest {
  userId: string;
  role: UserRole;
}

/** Admin API success envelope. */
export interface AdminApiResponse<T> {
  ok: true;
  data: T;
}

/** Admin API error envelope (403 non-admin, 404, 400 validation). */
export interface AdminApiError {
  ok: false;
  error: string;
}

/* ------------------------------------------------------------------ */
/*  Paywall (Decide/Learn) — locked content surface                    */
/* ------------------------------------------------------------------ */

/** Access options surfaced on the paywall for a locked course. */
export interface PaywallAccessOption {
  model: AccessModel;
  /** e.g. "$299 one-time", "Subscribe for access", "Granted by admin". */
  label: string;
  /** True when this option is actionable (vs informational "granted"). */
  actionable: boolean;
}

/** Paywall props — server-rendered with the course's real access options. */
export interface PaywallView {
  courseName: string;
  gradient: string;
  /** First lesson slug readable as the peek (may be null). */
  peekLessonSlug: string | null;
  options: PaywallAccessOption[];
}
