import { LearnLesson, LearningSeries } from "./types";

/**
 * GENERATED by scripts/build-learn.js. DO NOT HAND-EDIT.
 * Run `node scripts/build-learn.js` (or npm run prebuild) to regenerate.
 */

/** All series, sorted by newest lesson date DESC (ties → slug asc). Empty dirs included with lessons: []. */
export const learnSeries: LearningSeries[] = [
  {
    "slug": "agentic-ai",
    "name": "Agentic AI Implementation Path",
    "description": "From single-agent prototypes to multi-agent orchestration, a practitioner's curriculum for shipping agentic systems.",
    "gradient": "from-amber to-yellow-600",
    "lessons": [
      {
        "slug": "what-is-an-agent",
        "title": "Lesson 1: What an Agent Actually Is (LLMs vs Rules vs Workflows)",
        "series": "agentic-ai",
        "lesson": 1,
        "excerpt": "The definitions that matter for the whole 90-lesson track: what separates a rules system, an LLM workflow, and a true agent, plus how to tell which one you're actually building.",
        "date": "August 04, 2026",
        "author": "Adroit Consulting",
        "readTime": "9 min read",
        "tags": [
          "Learn",
          "AI",
          "Agentic",
          "Foundations"
        ],
        "status": "published"
      },
      {
        "slug": "how-llms-work-tokens-context-inference",
        "title": "Lesson 2: How LLMs Work for Implementers: Tokens, Context, Inference, Temperature",
        "series": "agentic-ai",
        "lesson": 2,
        "excerpt": "The four knobs that decide every LLM bill, latency budget, and reliability call: what tokens actually are, how the context window constrains agents, how inference really runs, and what temperature does and doesn't do.",
        "date": "August 05, 2026",
        "author": "Adroit Consulting",
        "readTime": "9 min read",
        "tags": [
          "Learn",
          "AI",
          "Agentic",
          "Foundations"
        ],
        "status": "published"
      },
      {
        "slug": "the-agent-loop-perceive-reason-act-observe",
        "title": "Lesson 3: The Agent Loop: Perceive, Reason, Act, Observe, and Where Your Code Lives",
        "series": "agentic-ai",
        "lesson": 3,
        "excerpt": "The one while loop that turns a language model into an agent: the five stages of the loop, the pseudocode that runs underneath every framework, and exactly which parts of it are your code versus the runtime's.",
        "date": "August 06, 2026",
        "author": "Adroit Consulting",
        "readTime": "9 min read",
        "tags": [
          "Learn",
          "AI",
          "Agentic",
          "Foundations"
        ],
        "status": "published"
      },
      {
        "slug": "prompting-for-agents-system-prompts-few-shot",
        "title": "Lesson 4: Prompting for Agents: System Prompts, Few-Shot, and When Prompts Aren't Enough",
        "series": "agentic-ai",
        "lesson": 4,
        "excerpt": "In an agent, the prompt isn't a single message; it's the constitution the loop obeys on every iteration. The anatomy of a production system prompt, how few-shot examples actually work, and the escalation ladder for when words stop being enough.",
        "date": "August 07, 2026",
        "author": "Adroit Consulting",
        "readTime": "10 min read",
        "tags": [
          "Learn",
          "AI",
          "Agentic",
          "Prompting"
        ],
        "status": "published"
      },
      {
        "slug": "tokens-context-cost-engineering-agents",
        "title": "Lesson 5: Tokens, Context Windows, and Cost Engineering for Agent Workloads",
        "series": "agentic-ai",
        "lesson": 5,
        "excerpt": "Agents don't just use tokens; they burn them: roughly 4x a chat conversation, 15x for multi-agent. The four levers that control the bill (budgeting, compression, caching, and model routing), with the math worked out on a real 10-agent pipeline.",
        "date": "August 08, 2026",
        "author": "Adroit Consulting",
        "readTime": "9 min read",
        "tags": [
          "Learn",
          "AI",
          "Agentic",
          "Cost"
        ],
        "status": "published"
      },
      {
        "slug": "choosing-models-providers-routing-fallbacks",
        "title": "Lesson 6: Choosing Models & Providers: Capability Tiers, Routing, and Fallbacks",
        "series": "agentic-ai",
        "lesson": 6,
        "excerpt": "The biggest agent-ops mistake is picking one 'best' model and pointing everything at it. This lesson builds the three-tier capability model, the three jobs of a router, and the fallback chains that keep agents alive when providers fail.",
        "date": "August 09, 2026",
        "author": "Adroit Consulting",
        "readTime": "8 min read",
        "tags": [
          "Learn",
          "AI",
          "Agentic",
          "Models"
        ],
        "status": "published"
      },
      {
        "slug": "structured-output-json-mode-function-calling-tool-schemas",
        "title": "Lesson 7: Structured Output: JSON Mode, Function Calling, and Tool Schemas Done Right",
        "series": "agentic-ai",
        "lesson": 7,
        "excerpt": "An agent is only as reliable as its data contracts. This lesson builds the structured-output ladder (JSON mode, Structured Outputs, function calling) and the tool-schema practices that keep tool calls valid, parseable, and safe in production.",
        "date": "August 10, 2026",
        "author": "Adroit Consulting",
        "readTime": "8 min read",
        "tags": [
          "Learn",
          "AI",
          "Agentic",
          "Tools"
        ],
        "status": "published"
      },
      {
        "slug": "tool-design-schemas-error-handling-retries",
        "title": "Lesson 8: Designing Tools That Fail Well: Schemas, Error Handling, and Retries",
        "series": "agentic-ai",
        "lesson": 8,
        "excerpt": "A tool is an operational contract, not an API wrapper. This lesson covers the five-part anatomy of a production tool, structured error schemas the model can act on, and retry discipline (backoff with jitter, idempotency keys, and retry budgets), so agents survive failures without corrupting state.",
        "date": "August 11, 2026",
        "author": "Adroit Consulting",
        "readTime": "9 min read",
        "tags": [
          "Learn",
          "AI",
          "Agentic",
          "Tools"
        ],
        "status": "published"
      },
      {
        "slug": "function-calling-parity-across-providers",
        "title": "Lesson 9: Function-Calling Parity Across OpenAI, Azure, Anthropic, Gemini, and Local Models",
        "series": "agentic-ai",
        "lesson": 9,
        "excerpt": "Every frontier provider exposes function calling, but none uses the same wire format. This lesson maps the request and response shapes across OpenAI, Azure, Anthropic, and Gemini, then shows why local models (llama.cpp) are the parity wildcard and how one internal schema plus thin per-provider adapters keeps an agent portable.",
        "date": "August 12, 2026",
        "author": "Adroit Consulting",
        "readTime": "9 min read",
        "tags": [
          "Learn",
          "AI",
          "Agentic",
          "Tools"
        ],
        "status": "published"
      },
      {
        "slug": "rag-fundamentals-chunking-embeddings-retrieval",
        "title": "Lesson 10: RAG Fundamentals: Chunking, Embeddings, Retrieval, and Why RAG Is the First Enterprise Pattern",
        "series": "agentic-ai",
        "lesson": 10,
        "excerpt": "The pattern that grounds LLMs in your own knowledge: what RAG is and where it came from, why you chunk documents instead of feeding them whole, what embeddings actually are, how retrieval ranks chunks, and why RAG became the first pattern enterprises shipped.",
        "date": "August 13, 2026",
        "author": "Adroit Consulting",
        "readTime": "10 min read",
        "tags": [
          "Learn",
          "AI",
          "Agentic",
          "RAG"
        ],
        "status": "published"
      },
      {
        "slug": "embeddings-models-similarity-when-they-fail",
        "title": "Lesson 11: Embeddings: Models, Similarity, and When They Fail",
        "series": "agentic-ai",
        "lesson": 11,
        "excerpt": "What an embedding actually is, how the popular models differ, why cosine similarity works, and the failure modes that make pure vector search miss the answer: rare terms, domain jargon, short queries, and model mismatch.",
        "date": "August 14, 2026",
        "author": "Adroit Consulting",
        "readTime": "10 min read",
        "tags": [
          "Learn",
          "AI",
          "Agentic",
          "Embeddings"
        ],
        "status": "published"
      },
      {
        "slug": "vector-databases-pinecone-pgvector-milvus-weaviate",
        "title": "Lesson 12: Vector Databases: Pinecone, pgvector, Milvus, Weaviate, and Choosing for Your Workload",
        "series": "agentic-ai",
        "lesson": 12,
        "excerpt": "What a vector database actually does, why you need one instead of scanning vectors in memory, the approximate nearest neighbor tradeoff you are making, and how to choose between Pinecone, pgvector, Milvus, and Weaviate for your workload and your team.",
        "date": "August 15, 2026",
        "author": "Adroit Consulting",
        "readTime": "10 min read",
        "tags": [
          "Learn",
          "AI",
          "Agentic",
          "Vector Databases"
        ],
        "status": "published"
      },
      {
        "slug": "rag-quality-reranking-hybrid-search-metadata-filtering-freshness",
        "title": "Lesson 13: RAG Quality: Reranking, Hybrid Search, Metadata Filtering, and Freshness",
        "series": "agentic-ai",
        "lesson": 13,
        "excerpt": "The four levers that turn a RAG demo into a system you can trust: reranking to fix top-k precision, hybrid search so exact terms still win, metadata filtering so access control and scope survive retrieval, and freshness so the answers do not go stale.",
        "date": "August 16, 2026",
        "author": "Adroit Consulting",
        "readTime": "12 min read",
        "tags": [
          "Learn",
          "AI",
          "Agentic",
          "RAG"
        ],
        "status": "published"
      },
      {
        "slug": "agent-memory-short-term-long-term-episodic-semantic",
        "title": "Lesson 14: Agent Memory: Short-Term vs Long-Term, Episodic vs Semantic",
        "series": "agentic-ai",
        "lesson": 14,
        "excerpt": "An agent with no memory answers the same question the same way forever. This lesson maps the memory taxonomy production systems borrow from cognitive science: the context window as working memory, long-term stores for persistence, episodic memory for what happened, semantic memory for what you know, and the pipeline that turns raw interactions into retrievable knowledge.",
        "date": "August 17, 2026",
        "author": "Adroit Consulting",
        "readTime": "10 min read",
        "tags": [
          "Learn",
          "AI",
          "Agentic",
          "Memory"
        ],
        "status": "published"
      },
      {
        "slug": "context-engineering-what-to-include-trimming-summarization-windowing",
        "title": "Lesson 15: Context Engineering: What to Include, Trim, Summarize, and Window",
        "series": "agentic-ai",
        "lesson": 15,
        "excerpt": "The context window is finite and filling it sloppily degrades your agent before it ever fails. This lesson covers the four ways to keep a long-running loop coherent: deciding what to include, trimming what stops earning its keep, summarizing what still matters, and windowing what you can drop. With real numbers from JetBrains on which approach actually pays.",
        "date": "August 18, 2026",
        "author": "Adroit Consulting",
        "readTime": "10 min read",
        "tags": [
          "Learn",
          "AI",
          "Agentic",
          "Context"
        ],
        "status": "published"
      }
    ],
    "totalLessons": 15
  },
  {
    "slug": "ai-at-work",
    "name": "AI at Work",
    "description": "A vendor-agnostic, 30-lesson primer for using AI in day-to-day work: foundations, prompting, productivity, small automations, and team adoption. Company-wide training that works for any team and any AI tool.",
    "gradient": "from-fuchsia to-purple-600",
    "lessons": [
      {
        "slug": "what-ai-actually-is",
        "title": "Lesson 1: What AI Actually Is",
        "series": "ai-at-work",
        "lesson": 1,
        "excerpt": "The words around AI are doing more confusing than clarifying. This lesson separates the four that trip up most people: models vs automation, chatbots vs tools, plus why 'LLM' and 'generative AI' are not synonyms.",
        "date": "August 16, 2026",
        "author": "Adroit Consulting",
        "readTime": "8 min read",
        "tags": [
          "Learn",
          "AI",
          "Workplace",
          "Foundations"
        ],
        "status": "published"
      },
      {
        "slug": "how-ai-thinks",
        "title": "Lesson 2: How AI Thinks in Plain Language",
        "series": "ai-at-work",
        "lesson": 2,
        "excerpt": "The tools you use every day do not read like you do. They read text in chunks called tokens, predict the next chunk over and over, and can only see a limited slice of the conversation at once. This lesson explains those three ideas and what they mean for how you prompt.",
        "date": "August 17, 2026",
        "author": "Adroit Consulting",
        "readTime": "8 min read",
        "tags": [
          "Learn",
          "AI",
          "Workplace",
          "Foundations"
        ],
        "status": "published"
      },
      {
        "slug": "hallucinations-what-they-are-and-how-to-catch-them",
        "title": "Lesson 3: Hallucinations, and How to Catch Them",
        "series": "ai-at-work",
        "lesson": 3,
        "excerpt": "AI tools make things up, and they do it in a confident voice. This lesson explains what a hallucination actually is, why a next-word predictor produces them, and the practical habits for catching them before they reach your work.",
        "date": "August 18, 2026",
        "author": "Adroit Consulting",
        "readTime": "8 min read",
        "tags": [
          "Learn",
          "AI",
          "Workplace",
          "Foundations"
        ],
        "status": "published"
      }
    ],
    "totalLessons": 3
  },
  {
    "slug": "omni-studio-cert",
    "name": "OmniStudio Developer Certification",
    "description": "A 46-requirement deep dive for the Salesforce Certified OmniStudio Developer exam. One official exam-guide requirement per day, with config walkthroughs, exam traps, and practice questions.",
    "group": "Salesforce Certifications",
    "subgroup": "Developer",
    "gradient": "from-red to-rose-600",
    "lessons": [
      {
        "slug": "day-01-f1-omnistudio-solution-and-industry-use-cases",
        "title": "OmniStudio F-1: OmniStudio Solution & Industry Use Cases",
        "series": "omni-studio-cert",
        "lesson": 1,
        "excerpt": "Describe the OmniStudio solution as it applies to common customer use case scenarios in different industries (telco, energy, healthcare, public sector, etc.). Day 1 of the 46-requirement OmniStudio Developer exam prep.",
        "date": "August 03, 2026",
        "author": "Adroit Consulting",
        "readTime": "6 min read",
        "tags": [
          "OmniStudio",
          "OmniStudio Fundamentals"
        ],
        "status": "published"
      },
      {
        "slug": "day-02-f2-project-needs-requirements-assumptions-risks-const",
        "title": "OmniStudio F-2: Project Needs: Requirements, Assumptions, Risks, Constraints",
        "series": "omni-studio-cert",
        "lesson": 2,
        "excerpt": "Determine a project's needs by evaluating a customer's requirements, assumptions, risks, and constraints. Day 2 of the 46-requirement OmniStudio Developer exam prep.",
        "date": "August 04, 2026",
        "author": "Adroit Consulting",
        "readTime": "6 min read",
        "tags": [
          "OmniStudio",
          "OmniStudio Fundamentals"
        ],
        "status": "published"
      },
      {
        "slug": "day-03-f3-managed-package-vs-standard-runtime-upgrades",
        "title": "OmniStudio F-3: Managed Package vs Standard Runtime; Upgrades",
        "series": "omni-studio-cert",
        "lesson": 3,
        "excerpt": "Explain Managed Package Runtime vs. Standard Runtime, Automatic Upgrades, and Manual Intervention Upgrade. Day 3 of the 46-requirement OmniStudio Developer exam prep.",
        "date": "August 05, 2026",
        "author": "Adroit Consulting",
        "readTime": "6 min read",
        "tags": [
          "OmniStudio",
          "OmniStudio Fundamentals"
        ],
        "status": "published"
      },
      {
        "slug": "day-04-f4-licensing-permission-set-licenses-permission-sets",
        "title": "OmniStudio F-4: Licensing, Permission Set Licenses & Permission Sets",
        "series": "omni-studio-cert",
        "lesson": 4,
        "excerpt": "Explain OmniStudio license requirements, Permission Set licenses and Permission Sets. Day 4 of the 46-requirement OmniStudio Developer exam prep.",
        "date": "August 06, 2026",
        "author": "Adroit Consulting",
        "readTime": "6 min read",
        "tags": [
          "OmniStudio",
          "OmniStudio Fundamentals"
        ],
        "status": "published"
      },
      {
        "slug": "day-05-f5-implementation-toolchain-sfcli-vbt-migration",
        "title": "OmniStudio F-5: Implementation Toolchain: SFCLI, VBT, Migration",
        "series": "omni-studio-cert",
        "lesson": 5,
        "excerpt": "Describe the tools required to complete the end-to-end implementation process (SFCLI, VBT, Migration, etc.). Day 5 of the 46-requirement OmniStudio Developer exam prep.",
        "date": "August 07, 2026",
        "author": "Adroit Consulting",
        "readTime": "6 min read",
        "tags": [
          "OmniStudio",
          "OmniStudio Fundamentals"
        ],
        "status": "published"
      },
      {
        "slug": "day-06-f-6-testing-versioning-cloning",
        "title": "OmniStudio F-6: Testing, Versioning & Cloning Components",
        "series": "omni-studio-cert",
        "lesson": 6,
        "excerpt": "Explain testing, versioning, and cloning through OmniStudio components. This covers save vs. publish, cloning workflows, and version snapshots for deployment.",
        "date": "August 8, 2026",
        "author": "Adroit Consulting",
        "readTime": "10 min read",
        "tags": [
          "OmniStudio",
          "OmniStudio Fundamentals"
        ],
        "status": "published"
      },
      {
        "slug": "day-07-fc-1-flexcard-data-sources-testing-json",
        "title": "OmniStudio FC-1: FlexCard Data Sources & Testing JSON",
        "series": "omni-studio-cert",
        "lesson": 7,
        "excerpt": "Configure data sources such as SOQL, Data Mapper, Integration Procedure, Custom, etc. and test resulting JSON structure.",
        "date": "August 9, 2026",
        "author": "Adroit Consulting",
        "readTime": "8 min read",
        "tags": [
          "OmniStudio",
          "FlexCards"
        ],
        "status": "published"
      },
      {
        "slug": "day-08-fc-2-single-multi-level-cards-layouts-repeaters",
        "title": "OmniStudio FC-2: Single/Multi-Level Cards, Layouts & Repeaters",
        "series": "omni-studio-cert",
        "lesson": 8,
        "excerpt": "Construct single and multi-level FlexCards, organizing data using layouts, and repeaters.",
        "date": "August 10, 2026",
        "author": "Adroit Consulting",
        "readTime": "6 min read",
        "tags": [
          "OmniStudio",
          "FlexCards"
        ],
        "status": "published"
      },
      {
        "slug": "day-09-fc-3-binding-components-configuring-properties",
        "title": "OmniStudio FC-3: Binding Components & Configuring Properties",
        "series": "omni-studio-cert",
        "lesson": 9,
        "excerpt": "Bind essential components to construct FlexCards and configure their properties.",
        "date": "August 11, 2026",
        "author": "Adroit Consulting",
        "readTime": "6 min read",
        "tags": [
          "OmniStudio",
          "FlexCards"
        ],
        "status": "published"
      },
      {
        "slug": "day-10-fc-4-complex-card-actions-launch-fire-update",
        "title": "OmniStudio FC-4: Complex Card Actions (Launch, Fire, Update)",
        "series": "omni-studio-cert",
        "lesson": 10,
        "excerpt": "Define and implement complex card actions, including launching OmniScripts, firing events, and updating other components.",
        "date": "August 12, 2026",
        "author": "Adroit Consulting",
        "readTime": "6 min read",
        "tags": [
          "OmniStudio",
          "FlexCards"
        ],
        "status": "published"
      },
      {
        "slug": "day-11-fc-5-advanced-flexcard-properties",
        "title": "OmniStudio FC-5: Advanced FlexCard Properties",
        "series": "omni-studio-cert",
        "lesson": 11,
        "excerpt": "Configure advanced FlexCard properties: Event Listeners, Session Variables, Public Attributes, multi-language, child FlexCards, and custom LWC integration.",
        "date": "August 13, 2026",
        "author": "Adroit Consulting",
        "readTime": "6 min read",
        "tags": [
          "OmniStudio",
          "FlexCards"
        ],
        "status": "published"
      },
      {
        "slug": "day-12-fc-6-flexcard-styling-themes",
        "title": "OmniStudio FC-6: FlexCard Styling & Themes",
        "series": "omni-studio-cert",
        "lesson": 12,
        "excerpt": "Control FlexCard appearance two ways: element-level inline styling for one-off tweaks and shared themes for consistent branding.",
        "date": "August 14, 2026",
        "author": "Adroit Consulting",
        "readTime": "5 min read",
        "tags": [
          "OmniStudio",
          "FlexCards"
        ],
        "status": "published"
      },
      {
        "slug": "day-13-fc-7-conditional-rendering-with-states",
        "title": "OmniStudio FC-7: Conditional Rendering with States",
        "series": "omni-studio-cert",
        "lesson": 13,
        "excerpt": "Use FlexCard states and element-level conditions to show, hide, or restyle content when expressions against card data evaluate true.",
        "date": "August 15, 2026",
        "author": "Adroit Consulting",
        "readTime": "5 min read",
        "tags": [
          "OmniStudio",
          "FlexCards"
        ],
        "status": "published"
      },
      {
        "slug": "day-14-fc-8-embedding-flexcards-across-channels",
        "title": "OmniStudio FC-8: Embedding FlexCards Across Channels",
        "series": "omni-studio-cert",
        "lesson": 14,
        "excerpt": "Embed one FlexCard definition across Lightning pages, Experience Cloud sites, OmniScripts, and mobile, and design it for reuse with public attributes.",
        "date": "August 16, 2026",
        "author": "Adroit Consulting",
        "readTime": "5 min read",
        "tags": [
          "OmniStudio",
          "FlexCards"
        ],
        "status": "published"
      },
      {
        "slug": "day-15-fc-9-flexcard-best-practices",
        "title": "OmniStudio FC-9: FlexCard Best Practices",
        "series": "omni-studio-cert",
        "lesson": 15,
        "excerpt": "Validate your JSON, keep data sources lean, test every state and channel, and respect FLS. That combination is what separates a card that survives production from one that goes blank.",
        "date": "August 17, 2026",
        "author": "Adroit Consulting",
        "readTime": "5 min read",
        "tags": [
          "OmniStudio",
          "FlexCards"
        ],
        "status": "published"
      },
      {
        "slug": "day-16-os-1-omniscript-elements-dynamic-interactions",
        "title": "OmniStudio OS-1: OmniScript Elements & Dynamic Interactions",
        "series": "omni-studio-cert",
        "lesson": 16,
        "excerpt": "OmniScripts are guided journeys built from named elements that all land in one data JSON. If you understand that JSON contract, formulas, actions, and debugging all follow. If you don't, nothing else works.",
        "date": "August 18, 2026",
        "author": "Adroit Consulting",
        "readTime": "6 min read",
        "tags": [
          "OmniStudio",
          "OmniScripts"
        ],
        "status": "published"
      }
    ],
    "totalLessons": 16
  },
  {
    "slug": "salesforce-architect",
    "name": "Salesforce System Architect Primer",
    "description": "A 90-lesson deep dive into Flow design, Apex patterns, and platform architecture for teams scaling on Salesforce.",
    "gradient": "from-sky to-blue-600",
    "lessons": [
      {
        "slug": "what-salesforce-system-architect-does",
        "title": "Lesson 1: What a Salesforce System Architect Actually Does: Role, Cert Track, CTA Endgame",
        "series": "salesforce-architect",
        "lesson": 1,
        "excerpt": "The Salesforce architect arc in one lesson: what System vs Application vs Technical Architects actually do, the certification ladder, and the CTA endgame.",
        "date": "August 04, 2026",
        "author": "Adroit Consulting",
        "readTime": "8 min read",
        "tags": [
          "Learn",
          "Salesforce",
          "Architect",
          "Certifications"
        ],
        "status": "published"
      },
      {
        "slug": "multi-tenant-platform-architecture",
        "title": "Lesson 2: Multi-Tenant Platform Architecture: Orgs, Environments, and the Instance Model",
        "series": "salesforce-architect",
        "lesson": 2,
        "excerpt": "Why every Salesforce org rents a slice of a shared platform: multi-tenancy, metadata-driven design, the instance model, and the sandbox environments that keep Dev/QA/UAT/Prod safe.",
        "date": "August 05, 2026",
        "author": "Adroit Consulting",
        "readTime": "8 min read",
        "tags": [
          "Learn",
          "Salesforce",
          "Architect",
          "Multi-Tenancy"
        ],
        "status": "published"
      },
      {
        "slug": "core-building-blocks-objects-fields-relationships",
        "title": "Lesson 3: Core Building Blocks: Objects, Fields, Relationships, Record Types, and Formula vs Roll-Up",
        "series": "salesforce-architect",
        "lesson": 3,
        "excerpt": "The architect's canvas: standard and custom objects, field types, lookup vs master-detail relationships, record types for process variation, and when to compute with a formula field vs a roll-up summary.",
        "date": "August 06, 2026",
        "author": "Adroit Consulting",
        "readTime": "8 min read",
        "tags": [
          "Learn",
          "Salesforce",
          "Architect",
          "Data Model"
        ],
        "status": "published"
      },
      {
        "slug": "integration-fundamentals-rest-soap-bulk-apis",
        "title": "Lesson 4: Integration Fundamentals: REST, SOAP, Bulk APIs, and Picking the Right One",
        "series": "salesforce-architect",
        "lesson": 4,
        "excerpt": "The System Architect's home turf: when to call Salesforce with REST, when to reach for SOAP, when to hand it a CSV via Bulk API 2.0, and the request limits that make the choice matter.",
        "date": "August 07, 2026",
        "author": "Adroit Consulting",
        "readTime": "9 min read",
        "tags": [
          "Learn",
          "Salesforce",
          "Architect",
          "Integration"
        ],
        "status": "published"
      },
      {
        "slug": "systems-architecture-what-it-means-ai-patterns",
        "title": "Lesson 5: General Systems Architecture: What 'Architecture' Means and Why AI Systems Reuse the Same Patterns",
        "series": "salesforce-architect",
        "lesson": 5,
        "excerpt": "The foundational concepts of systems architecture (components, interfaces, and design principles) and why every AI agent pattern (sequential, parallel, hierarchical) is a remix of patterns engineers have known for decades.",
        "date": "August 08, 2026",
        "author": "Adroit Consulting",
        "readTime": "9 min read",
        "tags": [
          "Learn",
          "Architect",
          "Systems Architecture",
          "AI Patterns",
          "General"
        ],
        "status": "published"
      },
      {
        "slug": "integration-patterns-request-reply-fire-forget-batch",
        "title": "Lesson 6: Integration Patterns: Request-Reply, Fire-and-Forget, and Batch (Inbound & Outbound)",
        "series": "salesforce-architect",
        "lesson": 6,
        "excerpt": "The three archetype integration patterns every Salesforce architect must recognize (request-reply, fire-and-forget, and batch data synchronization), plus the selection matrix, the limits that shape each choice, and a worked example that combines all three.",
        "date": "August 09, 2026",
        "author": "Adroit Consulting",
        "readTime": "9 min read",
        "tags": [
          "Learn",
          "Salesforce",
          "Architect",
          "Integration",
          "Integration Patterns"
        ],
        "status": "published"
      },
      {
        "slug": "event-driven-integration-platform-events-change-data-capture",
        "title": "Lesson 7: Event-Driven Integration: Platform Events + Change Data Capture",
        "series": "salesforce-architect",
        "lesson": 7,
        "excerpt": "The Salesforce event bus, Platform Events vs. Change Data Capture: when to publish business intent vs. record state, how to consume on- and off-platform, and the hard truth about ordering, replay, and allocations.",
        "date": "August 10, 2026",
        "author": "Adroit Consulting",
        "readTime": "8 min read",
        "tags": [
          "Learn",
          "Salesforce",
          "Architect",
          "Integration",
          "Platform Events",
          "Change Data Capture"
        ],
        "status": "published"
      },
      {
        "slug": "middleware-tradeoffs-mulesoft-boomi-custom-salesforce-hub",
        "title": "Lesson 8: Middleware Tradeoffs: MuleSoft vs Boomi vs Custom (and When Salesforce Is the Hub)",
        "series": "salesforce-architect",
        "lesson": 8,
        "excerpt": "How to choose the integration layer: MuleSoft's API-led pro-code platform, Boomi's low-code iPaaS, hand-rolled custom code, and the decision matrix for when Salesforce itself should be the hub instead of any middleware at all.",
        "date": "August 11, 2026",
        "author": "Adroit Consulting",
        "readTime": "9 min read",
        "tags": [
          "Learn",
          "Salesforce",
          "Architect",
          "Integration",
          "Middleware"
        ],
        "status": "published"
      },
      {
        "slug": "integration-reliability-idempotency-retries-error-handling-dead-letter-design",
        "title": "Lesson 9: Integration Reliability: Idempotency, Retries, Error Handling, and Dead-Letter Design",
        "series": "salesforce-architect",
        "lesson": 9,
        "excerpt": "The reliability toolkit every integration needs: idempotency keys and message IDs so retries are safe, the transient vs. poisoned error taxonomy, bounded retry policies with backoff, per-pattern error handling, and dead-letter design with error tables so nothing is silently lost.",
        "date": "August 12, 2026",
        "author": "Adroit Consulting",
        "readTime": "9 min read",
        "tags": [
          "Learn",
          "Salesforce",
          "Architect",
          "Integration",
          "Reliability",
          "Error Handling"
        ],
        "status": "published"
      },
      {
        "slug": "sync-async-queues-eventual-consistency-agent-pipelines",
        "title": "Lesson 10: Sync vs Async, Queues, and Eventual Consistency: The Laws That Shape Agent Pipelines",
        "series": "salesforce-architect",
        "lesson": 10,
        "excerpt": "The three operating laws that govern any pipeline spanning more than one system: synchronous calls block, asynchronous calls decouple, and distributed systems settle into eventual consistency. Queues are the buffer that makes async safe. And the same laws that drive Salesforce governor limits now shape multi-agent AI pipelines.",
        "date": "August 13, 2026",
        "author": "Adroit Consulting",
        "readTime": "9 min read",
        "tags": [
          "Learn",
          "Architect",
          "Systems Architecture",
          "Asynchronous",
          "Queues",
          "Eventual Consistency",
          "AI"
        ],
        "status": "published"
      },
      {
        "slug": "security-architecture-sharing-model-owd-role-hierarchy-sharing-rules",
        "title": "Lesson 11: Security Architecture: The Sharing Model, OWD, Role Hierarchy, Sharing Rules, and Manual Sharing",
        "series": "salesforce-architect",
        "lesson": 11,
        "excerpt": "Who can see a given record? The four record-level controls that answer it: org-wide defaults, the role hierarchy, sharing rules, and manual sharing. How they layer, how they only ever open access, and why 'most permissive wins' is the whole game.",
        "date": "August 14, 2026",
        "author": "Adroit Consulting",
        "readTime": "10 min read",
        "tags": [
          "Learn",
          "Salesforce",
          "Architect",
          "Security",
          "Sharing"
        ],
        "status": "published"
      },
      {
        "slug": "security-profiles-permission-sets-permission-set-groups-mfa-session-policies",
        "title": "Lesson 12: Security, Part 2: Profiles, Permission Sets, Permission Set Groups, MFA, and Session Policies",
        "series": "salesforce-architect",
        "lesson": 12,
        "excerpt": "Who can do what in an org. The move from profile-led to permission-set-led access, what a permission set group bundles together, the 2026 MFA enforcement that now touches every login, and the session policies that decide how long a session lives.",
        "date": "August 15, 2026",
        "author": "Adroit Consulting",
        "readTime": "10 min read",
        "tags": [
          "Learn",
          "Salesforce",
          "Architect",
          "Security",
          "Permissions"
        ],
        "status": "published"
      },
      {
        "slug": "security-external-access-oauth-saml-connected-apps-communities",
        "title": "Lesson 13: Security, Part 3: External Access, OAuth, SAML/SSO, Connected Apps, and Communities",
        "series": "salesforce-architect",
        "lesson": 13,
        "excerpt": "How outside systems and outside people get in. OAuth flows for machine access, SAML single sign-on for employee logins, connected apps as the doorway, and Experience Cloud communities as the portal where customers and partners authenticate without touching your internal identity system.",
        "date": "August 16, 2026",
        "author": "Adroit Consulting",
        "readTime": "11 min read",
        "tags": [
          "Learn",
          "Salesforce",
          "Architect",
          "Security",
          "Identity",
          "OAuth",
          "SAML",
          "Communities"
        ],
        "status": "published"
      },
      {
        "slug": "data-architecture-data-model-design-patterns-data-skew",
        "title": "Lesson 14: Data Architecture: Data Model Design, Common Data Model Patterns, and Data Skew",
        "series": "salesforce-architect",
        "lesson": 14,
        "excerpt": "Data is the load-bearing wall of every org. Designing a data model that scales means deciding where each relationship lives, recognizing the recurring shapes that solve real problems, and keeping the load off any single parent record or owner. This lesson covers data model design, the common patterns (one-to-many, many-to-many, hierarchical, and data tiering), and the three data skews that quietly break performance.",
        "date": "August 17, 2026",
        "author": "Adroit Consulting",
        "readTime": "11 min read",
        "tags": [
          "Learn",
          "Salesforce",
          "Architect",
          "Data Model",
          "Data Architecture"
        ],
        "status": "published"
      },
      {
        "slug": "data-architecture-for-ai-vector-databases-embeddings",
        "title": "Lesson 15: Data Architecture for AI: Databases, Vector DBs, Embeddings, and the Same Modeling Discipline",
        "series": "salesforce-architect",
        "lesson": 15,
        "excerpt": "The data side of AI systems. Embeddings, vector databases, chunking, and why the modeling discipline from a Salesforce data model (records, relationships, source of truth, scale) carries over unchanged when the storage engine becomes a vector store. Includes a worked example of a RAG knowledge base, a pgvector walkthrough, and the Data Cloud vector database connection.",
        "date": "August 18, 2026",
        "author": "Adroit Consulting",
        "readTime": "10 min read",
        "tags": [
          "Learn",
          "Architect",
          "Data Architecture",
          "AI",
          "Vector Database"
        ],
        "status": "published"
      }
    ],
    "totalLessons": 15
  }
];

/** Flat list of every lesson, NEWEST FIRST (for sitemap, nav, flat lookups). */
export const learnLessons: LearnLesson[] = [
  {
    "slug": "context-engineering-what-to-include-trimming-summarization-windowing",
    "title": "Lesson 15: Context Engineering: What to Include, Trim, Summarize, and Window",
    "series": "agentic-ai",
    "lesson": 15,
    "excerpt": "The context window is finite and filling it sloppily degrades your agent before it ever fails. This lesson covers the four ways to keep a long-running loop coherent: deciding what to include, trimming what stops earning its keep, summarizing what still matters, and windowing what you can drop. With real numbers from JetBrains on which approach actually pays.",
    "date": "August 18, 2026",
    "author": "Adroit Consulting",
    "readTime": "10 min read",
    "tags": [
      "Learn",
      "AI",
      "Agentic",
      "Context"
    ],
    "status": "published"
  },
  {
    "slug": "hallucinations-what-they-are-and-how-to-catch-them",
    "title": "Lesson 3: Hallucinations, and How to Catch Them",
    "series": "ai-at-work",
    "lesson": 3,
    "excerpt": "AI tools make things up, and they do it in a confident voice. This lesson explains what a hallucination actually is, why a next-word predictor produces them, and the practical habits for catching them before they reach your work.",
    "date": "August 18, 2026",
    "author": "Adroit Consulting",
    "readTime": "8 min read",
    "tags": [
      "Learn",
      "AI",
      "Workplace",
      "Foundations"
    ],
    "status": "published"
  },
  {
    "slug": "day-16-os-1-omniscript-elements-dynamic-interactions",
    "title": "OmniStudio OS-1: OmniScript Elements & Dynamic Interactions",
    "series": "omni-studio-cert",
    "lesson": 16,
    "excerpt": "OmniScripts are guided journeys built from named elements that all land in one data JSON. If you understand that JSON contract, formulas, actions, and debugging all follow. If you don't, nothing else works.",
    "date": "August 18, 2026",
    "author": "Adroit Consulting",
    "readTime": "6 min read",
    "tags": [
      "OmniStudio",
      "OmniScripts"
    ],
    "status": "published"
  },
  {
    "slug": "data-architecture-for-ai-vector-databases-embeddings",
    "title": "Lesson 15: Data Architecture for AI: Databases, Vector DBs, Embeddings, and the Same Modeling Discipline",
    "series": "salesforce-architect",
    "lesson": 15,
    "excerpt": "The data side of AI systems. Embeddings, vector databases, chunking, and why the modeling discipline from a Salesforce data model (records, relationships, source of truth, scale) carries over unchanged when the storage engine becomes a vector store. Includes a worked example of a RAG knowledge base, a pgvector walkthrough, and the Data Cloud vector database connection.",
    "date": "August 18, 2026",
    "author": "Adroit Consulting",
    "readTime": "10 min read",
    "tags": [
      "Learn",
      "Architect",
      "Data Architecture",
      "AI",
      "Vector Database"
    ],
    "status": "published"
  },
  {
    "slug": "agent-memory-short-term-long-term-episodic-semantic",
    "title": "Lesson 14: Agent Memory: Short-Term vs Long-Term, Episodic vs Semantic",
    "series": "agentic-ai",
    "lesson": 14,
    "excerpt": "An agent with no memory answers the same question the same way forever. This lesson maps the memory taxonomy production systems borrow from cognitive science: the context window as working memory, long-term stores for persistence, episodic memory for what happened, semantic memory for what you know, and the pipeline that turns raw interactions into retrievable knowledge.",
    "date": "August 17, 2026",
    "author": "Adroit Consulting",
    "readTime": "10 min read",
    "tags": [
      "Learn",
      "AI",
      "Agentic",
      "Memory"
    ],
    "status": "published"
  },
  {
    "slug": "how-ai-thinks",
    "title": "Lesson 2: How AI Thinks in Plain Language",
    "series": "ai-at-work",
    "lesson": 2,
    "excerpt": "The tools you use every day do not read like you do. They read text in chunks called tokens, predict the next chunk over and over, and can only see a limited slice of the conversation at once. This lesson explains those three ideas and what they mean for how you prompt.",
    "date": "August 17, 2026",
    "author": "Adroit Consulting",
    "readTime": "8 min read",
    "tags": [
      "Learn",
      "AI",
      "Workplace",
      "Foundations"
    ],
    "status": "published"
  },
  {
    "slug": "day-15-fc-9-flexcard-best-practices",
    "title": "OmniStudio FC-9: FlexCard Best Practices",
    "series": "omni-studio-cert",
    "lesson": 15,
    "excerpt": "Validate your JSON, keep data sources lean, test every state and channel, and respect FLS. That combination is what separates a card that survives production from one that goes blank.",
    "date": "August 17, 2026",
    "author": "Adroit Consulting",
    "readTime": "5 min read",
    "tags": [
      "OmniStudio",
      "FlexCards"
    ],
    "status": "published"
  },
  {
    "slug": "data-architecture-data-model-design-patterns-data-skew",
    "title": "Lesson 14: Data Architecture: Data Model Design, Common Data Model Patterns, and Data Skew",
    "series": "salesforce-architect",
    "lesson": 14,
    "excerpt": "Data is the load-bearing wall of every org. Designing a data model that scales means deciding where each relationship lives, recognizing the recurring shapes that solve real problems, and keeping the load off any single parent record or owner. This lesson covers data model design, the common patterns (one-to-many, many-to-many, hierarchical, and data tiering), and the three data skews that quietly break performance.",
    "date": "August 17, 2026",
    "author": "Adroit Consulting",
    "readTime": "11 min read",
    "tags": [
      "Learn",
      "Salesforce",
      "Architect",
      "Data Model",
      "Data Architecture"
    ],
    "status": "published"
  },
  {
    "slug": "rag-quality-reranking-hybrid-search-metadata-filtering-freshness",
    "title": "Lesson 13: RAG Quality: Reranking, Hybrid Search, Metadata Filtering, and Freshness",
    "series": "agentic-ai",
    "lesson": 13,
    "excerpt": "The four levers that turn a RAG demo into a system you can trust: reranking to fix top-k precision, hybrid search so exact terms still win, metadata filtering so access control and scope survive retrieval, and freshness so the answers do not go stale.",
    "date": "August 16, 2026",
    "author": "Adroit Consulting",
    "readTime": "12 min read",
    "tags": [
      "Learn",
      "AI",
      "Agentic",
      "RAG"
    ],
    "status": "published"
  },
  {
    "slug": "what-ai-actually-is",
    "title": "Lesson 1: What AI Actually Is",
    "series": "ai-at-work",
    "lesson": 1,
    "excerpt": "The words around AI are doing more confusing than clarifying. This lesson separates the four that trip up most people: models vs automation, chatbots vs tools, plus why 'LLM' and 'generative AI' are not synonyms.",
    "date": "August 16, 2026",
    "author": "Adroit Consulting",
    "readTime": "8 min read",
    "tags": [
      "Learn",
      "AI",
      "Workplace",
      "Foundations"
    ],
    "status": "published"
  },
  {
    "slug": "day-14-fc-8-embedding-flexcards-across-channels",
    "title": "OmniStudio FC-8: Embedding FlexCards Across Channels",
    "series": "omni-studio-cert",
    "lesson": 14,
    "excerpt": "Embed one FlexCard definition across Lightning pages, Experience Cloud sites, OmniScripts, and mobile, and design it for reuse with public attributes.",
    "date": "August 16, 2026",
    "author": "Adroit Consulting",
    "readTime": "5 min read",
    "tags": [
      "OmniStudio",
      "FlexCards"
    ],
    "status": "published"
  },
  {
    "slug": "security-external-access-oauth-saml-connected-apps-communities",
    "title": "Lesson 13: Security, Part 3: External Access, OAuth, SAML/SSO, Connected Apps, and Communities",
    "series": "salesforce-architect",
    "lesson": 13,
    "excerpt": "How outside systems and outside people get in. OAuth flows for machine access, SAML single sign-on for employee logins, connected apps as the doorway, and Experience Cloud communities as the portal where customers and partners authenticate without touching your internal identity system.",
    "date": "August 16, 2026",
    "author": "Adroit Consulting",
    "readTime": "11 min read",
    "tags": [
      "Learn",
      "Salesforce",
      "Architect",
      "Security",
      "Identity",
      "OAuth",
      "SAML",
      "Communities"
    ],
    "status": "published"
  },
  {
    "slug": "vector-databases-pinecone-pgvector-milvus-weaviate",
    "title": "Lesson 12: Vector Databases: Pinecone, pgvector, Milvus, Weaviate, and Choosing for Your Workload",
    "series": "agentic-ai",
    "lesson": 12,
    "excerpt": "What a vector database actually does, why you need one instead of scanning vectors in memory, the approximate nearest neighbor tradeoff you are making, and how to choose between Pinecone, pgvector, Milvus, and Weaviate for your workload and your team.",
    "date": "August 15, 2026",
    "author": "Adroit Consulting",
    "readTime": "10 min read",
    "tags": [
      "Learn",
      "AI",
      "Agentic",
      "Vector Databases"
    ],
    "status": "published"
  },
  {
    "slug": "day-13-fc-7-conditional-rendering-with-states",
    "title": "OmniStudio FC-7: Conditional Rendering with States",
    "series": "omni-studio-cert",
    "lesson": 13,
    "excerpt": "Use FlexCard states and element-level conditions to show, hide, or restyle content when expressions against card data evaluate true.",
    "date": "August 15, 2026",
    "author": "Adroit Consulting",
    "readTime": "5 min read",
    "tags": [
      "OmniStudio",
      "FlexCards"
    ],
    "status": "published"
  },
  {
    "slug": "security-profiles-permission-sets-permission-set-groups-mfa-session-policies",
    "title": "Lesson 12: Security, Part 2: Profiles, Permission Sets, Permission Set Groups, MFA, and Session Policies",
    "series": "salesforce-architect",
    "lesson": 12,
    "excerpt": "Who can do what in an org. The move from profile-led to permission-set-led access, what a permission set group bundles together, the 2026 MFA enforcement that now touches every login, and the session policies that decide how long a session lives.",
    "date": "August 15, 2026",
    "author": "Adroit Consulting",
    "readTime": "10 min read",
    "tags": [
      "Learn",
      "Salesforce",
      "Architect",
      "Security",
      "Permissions"
    ],
    "status": "published"
  },
  {
    "slug": "embeddings-models-similarity-when-they-fail",
    "title": "Lesson 11: Embeddings: Models, Similarity, and When They Fail",
    "series": "agentic-ai",
    "lesson": 11,
    "excerpt": "What an embedding actually is, how the popular models differ, why cosine similarity works, and the failure modes that make pure vector search miss the answer: rare terms, domain jargon, short queries, and model mismatch.",
    "date": "August 14, 2026",
    "author": "Adroit Consulting",
    "readTime": "10 min read",
    "tags": [
      "Learn",
      "AI",
      "Agentic",
      "Embeddings"
    ],
    "status": "published"
  },
  {
    "slug": "day-12-fc-6-flexcard-styling-themes",
    "title": "OmniStudio FC-6: FlexCard Styling & Themes",
    "series": "omni-studio-cert",
    "lesson": 12,
    "excerpt": "Control FlexCard appearance two ways: element-level inline styling for one-off tweaks and shared themes for consistent branding.",
    "date": "August 14, 2026",
    "author": "Adroit Consulting",
    "readTime": "5 min read",
    "tags": [
      "OmniStudio",
      "FlexCards"
    ],
    "status": "published"
  },
  {
    "slug": "security-architecture-sharing-model-owd-role-hierarchy-sharing-rules",
    "title": "Lesson 11: Security Architecture: The Sharing Model, OWD, Role Hierarchy, Sharing Rules, and Manual Sharing",
    "series": "salesforce-architect",
    "lesson": 11,
    "excerpt": "Who can see a given record? The four record-level controls that answer it: org-wide defaults, the role hierarchy, sharing rules, and manual sharing. How they layer, how they only ever open access, and why 'most permissive wins' is the whole game.",
    "date": "August 14, 2026",
    "author": "Adroit Consulting",
    "readTime": "10 min read",
    "tags": [
      "Learn",
      "Salesforce",
      "Architect",
      "Security",
      "Sharing"
    ],
    "status": "published"
  },
  {
    "slug": "rag-fundamentals-chunking-embeddings-retrieval",
    "title": "Lesson 10: RAG Fundamentals: Chunking, Embeddings, Retrieval, and Why RAG Is the First Enterprise Pattern",
    "series": "agentic-ai",
    "lesson": 10,
    "excerpt": "The pattern that grounds LLMs in your own knowledge: what RAG is and where it came from, why you chunk documents instead of feeding them whole, what embeddings actually are, how retrieval ranks chunks, and why RAG became the first pattern enterprises shipped.",
    "date": "August 13, 2026",
    "author": "Adroit Consulting",
    "readTime": "10 min read",
    "tags": [
      "Learn",
      "AI",
      "Agentic",
      "RAG"
    ],
    "status": "published"
  },
  {
    "slug": "day-11-fc-5-advanced-flexcard-properties",
    "title": "OmniStudio FC-5: Advanced FlexCard Properties",
    "series": "omni-studio-cert",
    "lesson": 11,
    "excerpt": "Configure advanced FlexCard properties: Event Listeners, Session Variables, Public Attributes, multi-language, child FlexCards, and custom LWC integration.",
    "date": "August 13, 2026",
    "author": "Adroit Consulting",
    "readTime": "6 min read",
    "tags": [
      "OmniStudio",
      "FlexCards"
    ],
    "status": "published"
  },
  {
    "slug": "sync-async-queues-eventual-consistency-agent-pipelines",
    "title": "Lesson 10: Sync vs Async, Queues, and Eventual Consistency: The Laws That Shape Agent Pipelines",
    "series": "salesforce-architect",
    "lesson": 10,
    "excerpt": "The three operating laws that govern any pipeline spanning more than one system: synchronous calls block, asynchronous calls decouple, and distributed systems settle into eventual consistency. Queues are the buffer that makes async safe. And the same laws that drive Salesforce governor limits now shape multi-agent AI pipelines.",
    "date": "August 13, 2026",
    "author": "Adroit Consulting",
    "readTime": "9 min read",
    "tags": [
      "Learn",
      "Architect",
      "Systems Architecture",
      "Asynchronous",
      "Queues",
      "Eventual Consistency",
      "AI"
    ],
    "status": "published"
  },
  {
    "slug": "function-calling-parity-across-providers",
    "title": "Lesson 9: Function-Calling Parity Across OpenAI, Azure, Anthropic, Gemini, and Local Models",
    "series": "agentic-ai",
    "lesson": 9,
    "excerpt": "Every frontier provider exposes function calling, but none uses the same wire format. This lesson maps the request and response shapes across OpenAI, Azure, Anthropic, and Gemini, then shows why local models (llama.cpp) are the parity wildcard and how one internal schema plus thin per-provider adapters keeps an agent portable.",
    "date": "August 12, 2026",
    "author": "Adroit Consulting",
    "readTime": "9 min read",
    "tags": [
      "Learn",
      "AI",
      "Agentic",
      "Tools"
    ],
    "status": "published"
  },
  {
    "slug": "day-10-fc-4-complex-card-actions-launch-fire-update",
    "title": "OmniStudio FC-4: Complex Card Actions (Launch, Fire, Update)",
    "series": "omni-studio-cert",
    "lesson": 10,
    "excerpt": "Define and implement complex card actions, including launching OmniScripts, firing events, and updating other components.",
    "date": "August 12, 2026",
    "author": "Adroit Consulting",
    "readTime": "6 min read",
    "tags": [
      "OmniStudio",
      "FlexCards"
    ],
    "status": "published"
  },
  {
    "slug": "integration-reliability-idempotency-retries-error-handling-dead-letter-design",
    "title": "Lesson 9: Integration Reliability: Idempotency, Retries, Error Handling, and Dead-Letter Design",
    "series": "salesforce-architect",
    "lesson": 9,
    "excerpt": "The reliability toolkit every integration needs: idempotency keys and message IDs so retries are safe, the transient vs. poisoned error taxonomy, bounded retry policies with backoff, per-pattern error handling, and dead-letter design with error tables so nothing is silently lost.",
    "date": "August 12, 2026",
    "author": "Adroit Consulting",
    "readTime": "9 min read",
    "tags": [
      "Learn",
      "Salesforce",
      "Architect",
      "Integration",
      "Reliability",
      "Error Handling"
    ],
    "status": "published"
  },
  {
    "slug": "tool-design-schemas-error-handling-retries",
    "title": "Lesson 8: Designing Tools That Fail Well: Schemas, Error Handling, and Retries",
    "series": "agentic-ai",
    "lesson": 8,
    "excerpt": "A tool is an operational contract, not an API wrapper. This lesson covers the five-part anatomy of a production tool, structured error schemas the model can act on, and retry discipline (backoff with jitter, idempotency keys, and retry budgets), so agents survive failures without corrupting state.",
    "date": "August 11, 2026",
    "author": "Adroit Consulting",
    "readTime": "9 min read",
    "tags": [
      "Learn",
      "AI",
      "Agentic",
      "Tools"
    ],
    "status": "published"
  },
  {
    "slug": "day-09-fc-3-binding-components-configuring-properties",
    "title": "OmniStudio FC-3: Binding Components & Configuring Properties",
    "series": "omni-studio-cert",
    "lesson": 9,
    "excerpt": "Bind essential components to construct FlexCards and configure their properties.",
    "date": "August 11, 2026",
    "author": "Adroit Consulting",
    "readTime": "6 min read",
    "tags": [
      "OmniStudio",
      "FlexCards"
    ],
    "status": "published"
  },
  {
    "slug": "middleware-tradeoffs-mulesoft-boomi-custom-salesforce-hub",
    "title": "Lesson 8: Middleware Tradeoffs: MuleSoft vs Boomi vs Custom (and When Salesforce Is the Hub)",
    "series": "salesforce-architect",
    "lesson": 8,
    "excerpt": "How to choose the integration layer: MuleSoft's API-led pro-code platform, Boomi's low-code iPaaS, hand-rolled custom code, and the decision matrix for when Salesforce itself should be the hub instead of any middleware at all.",
    "date": "August 11, 2026",
    "author": "Adroit Consulting",
    "readTime": "9 min read",
    "tags": [
      "Learn",
      "Salesforce",
      "Architect",
      "Integration",
      "Middleware"
    ],
    "status": "published"
  },
  {
    "slug": "structured-output-json-mode-function-calling-tool-schemas",
    "title": "Lesson 7: Structured Output: JSON Mode, Function Calling, and Tool Schemas Done Right",
    "series": "agentic-ai",
    "lesson": 7,
    "excerpt": "An agent is only as reliable as its data contracts. This lesson builds the structured-output ladder (JSON mode, Structured Outputs, function calling) and the tool-schema practices that keep tool calls valid, parseable, and safe in production.",
    "date": "August 10, 2026",
    "author": "Adroit Consulting",
    "readTime": "8 min read",
    "tags": [
      "Learn",
      "AI",
      "Agentic",
      "Tools"
    ],
    "status": "published"
  },
  {
    "slug": "day-08-fc-2-single-multi-level-cards-layouts-repeaters",
    "title": "OmniStudio FC-2: Single/Multi-Level Cards, Layouts & Repeaters",
    "series": "omni-studio-cert",
    "lesson": 8,
    "excerpt": "Construct single and multi-level FlexCards, organizing data using layouts, and repeaters.",
    "date": "August 10, 2026",
    "author": "Adroit Consulting",
    "readTime": "6 min read",
    "tags": [
      "OmniStudio",
      "FlexCards"
    ],
    "status": "published"
  },
  {
    "slug": "event-driven-integration-platform-events-change-data-capture",
    "title": "Lesson 7: Event-Driven Integration: Platform Events + Change Data Capture",
    "series": "salesforce-architect",
    "lesson": 7,
    "excerpt": "The Salesforce event bus, Platform Events vs. Change Data Capture: when to publish business intent vs. record state, how to consume on- and off-platform, and the hard truth about ordering, replay, and allocations.",
    "date": "August 10, 2026",
    "author": "Adroit Consulting",
    "readTime": "8 min read",
    "tags": [
      "Learn",
      "Salesforce",
      "Architect",
      "Integration",
      "Platform Events",
      "Change Data Capture"
    ],
    "status": "published"
  },
  {
    "slug": "choosing-models-providers-routing-fallbacks",
    "title": "Lesson 6: Choosing Models & Providers: Capability Tiers, Routing, and Fallbacks",
    "series": "agentic-ai",
    "lesson": 6,
    "excerpt": "The biggest agent-ops mistake is picking one 'best' model and pointing everything at it. This lesson builds the three-tier capability model, the three jobs of a router, and the fallback chains that keep agents alive when providers fail.",
    "date": "August 09, 2026",
    "author": "Adroit Consulting",
    "readTime": "8 min read",
    "tags": [
      "Learn",
      "AI",
      "Agentic",
      "Models"
    ],
    "status": "published"
  },
  {
    "slug": "day-07-fc-1-flexcard-data-sources-testing-json",
    "title": "OmniStudio FC-1: FlexCard Data Sources & Testing JSON",
    "series": "omni-studio-cert",
    "lesson": 7,
    "excerpt": "Configure data sources such as SOQL, Data Mapper, Integration Procedure, Custom, etc. and test resulting JSON structure.",
    "date": "August 9, 2026",
    "author": "Adroit Consulting",
    "readTime": "8 min read",
    "tags": [
      "OmniStudio",
      "FlexCards"
    ],
    "status": "published"
  },
  {
    "slug": "integration-patterns-request-reply-fire-forget-batch",
    "title": "Lesson 6: Integration Patterns: Request-Reply, Fire-and-Forget, and Batch (Inbound & Outbound)",
    "series": "salesforce-architect",
    "lesson": 6,
    "excerpt": "The three archetype integration patterns every Salesforce architect must recognize (request-reply, fire-and-forget, and batch data synchronization), plus the selection matrix, the limits that shape each choice, and a worked example that combines all three.",
    "date": "August 09, 2026",
    "author": "Adroit Consulting",
    "readTime": "9 min read",
    "tags": [
      "Learn",
      "Salesforce",
      "Architect",
      "Integration",
      "Integration Patterns"
    ],
    "status": "published"
  },
  {
    "slug": "tokens-context-cost-engineering-agents",
    "title": "Lesson 5: Tokens, Context Windows, and Cost Engineering for Agent Workloads",
    "series": "agentic-ai",
    "lesson": 5,
    "excerpt": "Agents don't just use tokens; they burn them: roughly 4x a chat conversation, 15x for multi-agent. The four levers that control the bill (budgeting, compression, caching, and model routing), with the math worked out on a real 10-agent pipeline.",
    "date": "August 08, 2026",
    "author": "Adroit Consulting",
    "readTime": "9 min read",
    "tags": [
      "Learn",
      "AI",
      "Agentic",
      "Cost"
    ],
    "status": "published"
  },
  {
    "slug": "day-06-f-6-testing-versioning-cloning",
    "title": "OmniStudio F-6: Testing, Versioning & Cloning Components",
    "series": "omni-studio-cert",
    "lesson": 6,
    "excerpt": "Explain testing, versioning, and cloning through OmniStudio components. This covers save vs. publish, cloning workflows, and version snapshots for deployment.",
    "date": "August 8, 2026",
    "author": "Adroit Consulting",
    "readTime": "10 min read",
    "tags": [
      "OmniStudio",
      "OmniStudio Fundamentals"
    ],
    "status": "published"
  },
  {
    "slug": "systems-architecture-what-it-means-ai-patterns",
    "title": "Lesson 5: General Systems Architecture: What 'Architecture' Means and Why AI Systems Reuse the Same Patterns",
    "series": "salesforce-architect",
    "lesson": 5,
    "excerpt": "The foundational concepts of systems architecture (components, interfaces, and design principles) and why every AI agent pattern (sequential, parallel, hierarchical) is a remix of patterns engineers have known for decades.",
    "date": "August 08, 2026",
    "author": "Adroit Consulting",
    "readTime": "9 min read",
    "tags": [
      "Learn",
      "Architect",
      "Systems Architecture",
      "AI Patterns",
      "General"
    ],
    "status": "published"
  },
  {
    "slug": "prompting-for-agents-system-prompts-few-shot",
    "title": "Lesson 4: Prompting for Agents: System Prompts, Few-Shot, and When Prompts Aren't Enough",
    "series": "agentic-ai",
    "lesson": 4,
    "excerpt": "In an agent, the prompt isn't a single message; it's the constitution the loop obeys on every iteration. The anatomy of a production system prompt, how few-shot examples actually work, and the escalation ladder for when words stop being enough.",
    "date": "August 07, 2026",
    "author": "Adroit Consulting",
    "readTime": "10 min read",
    "tags": [
      "Learn",
      "AI",
      "Agentic",
      "Prompting"
    ],
    "status": "published"
  },
  {
    "slug": "day-05-f5-implementation-toolchain-sfcli-vbt-migration",
    "title": "OmniStudio F-5: Implementation Toolchain: SFCLI, VBT, Migration",
    "series": "omni-studio-cert",
    "lesson": 5,
    "excerpt": "Describe the tools required to complete the end-to-end implementation process (SFCLI, VBT, Migration, etc.). Day 5 of the 46-requirement OmniStudio Developer exam prep.",
    "date": "August 07, 2026",
    "author": "Adroit Consulting",
    "readTime": "6 min read",
    "tags": [
      "OmniStudio",
      "OmniStudio Fundamentals"
    ],
    "status": "published"
  },
  {
    "slug": "integration-fundamentals-rest-soap-bulk-apis",
    "title": "Lesson 4: Integration Fundamentals: REST, SOAP, Bulk APIs, and Picking the Right One",
    "series": "salesforce-architect",
    "lesson": 4,
    "excerpt": "The System Architect's home turf: when to call Salesforce with REST, when to reach for SOAP, when to hand it a CSV via Bulk API 2.0, and the request limits that make the choice matter.",
    "date": "August 07, 2026",
    "author": "Adroit Consulting",
    "readTime": "9 min read",
    "tags": [
      "Learn",
      "Salesforce",
      "Architect",
      "Integration"
    ],
    "status": "published"
  },
  {
    "slug": "the-agent-loop-perceive-reason-act-observe",
    "title": "Lesson 3: The Agent Loop: Perceive, Reason, Act, Observe, and Where Your Code Lives",
    "series": "agentic-ai",
    "lesson": 3,
    "excerpt": "The one while loop that turns a language model into an agent: the five stages of the loop, the pseudocode that runs underneath every framework, and exactly which parts of it are your code versus the runtime's.",
    "date": "August 06, 2026",
    "author": "Adroit Consulting",
    "readTime": "9 min read",
    "tags": [
      "Learn",
      "AI",
      "Agentic",
      "Foundations"
    ],
    "status": "published"
  },
  {
    "slug": "day-04-f4-licensing-permission-set-licenses-permission-sets",
    "title": "OmniStudio F-4: Licensing, Permission Set Licenses & Permission Sets",
    "series": "omni-studio-cert",
    "lesson": 4,
    "excerpt": "Explain OmniStudio license requirements, Permission Set licenses and Permission Sets. Day 4 of the 46-requirement OmniStudio Developer exam prep.",
    "date": "August 06, 2026",
    "author": "Adroit Consulting",
    "readTime": "6 min read",
    "tags": [
      "OmniStudio",
      "OmniStudio Fundamentals"
    ],
    "status": "published"
  },
  {
    "slug": "core-building-blocks-objects-fields-relationships",
    "title": "Lesson 3: Core Building Blocks: Objects, Fields, Relationships, Record Types, and Formula vs Roll-Up",
    "series": "salesforce-architect",
    "lesson": 3,
    "excerpt": "The architect's canvas: standard and custom objects, field types, lookup vs master-detail relationships, record types for process variation, and when to compute with a formula field vs a roll-up summary.",
    "date": "August 06, 2026",
    "author": "Adroit Consulting",
    "readTime": "8 min read",
    "tags": [
      "Learn",
      "Salesforce",
      "Architect",
      "Data Model"
    ],
    "status": "published"
  },
  {
    "slug": "how-llms-work-tokens-context-inference",
    "title": "Lesson 2: How LLMs Work for Implementers: Tokens, Context, Inference, Temperature",
    "series": "agentic-ai",
    "lesson": 2,
    "excerpt": "The four knobs that decide every LLM bill, latency budget, and reliability call: what tokens actually are, how the context window constrains agents, how inference really runs, and what temperature does and doesn't do.",
    "date": "August 05, 2026",
    "author": "Adroit Consulting",
    "readTime": "9 min read",
    "tags": [
      "Learn",
      "AI",
      "Agentic",
      "Foundations"
    ],
    "status": "published"
  },
  {
    "slug": "day-03-f3-managed-package-vs-standard-runtime-upgrades",
    "title": "OmniStudio F-3: Managed Package vs Standard Runtime; Upgrades",
    "series": "omni-studio-cert",
    "lesson": 3,
    "excerpt": "Explain Managed Package Runtime vs. Standard Runtime, Automatic Upgrades, and Manual Intervention Upgrade. Day 3 of the 46-requirement OmniStudio Developer exam prep.",
    "date": "August 05, 2026",
    "author": "Adroit Consulting",
    "readTime": "6 min read",
    "tags": [
      "OmniStudio",
      "OmniStudio Fundamentals"
    ],
    "status": "published"
  },
  {
    "slug": "multi-tenant-platform-architecture",
    "title": "Lesson 2: Multi-Tenant Platform Architecture: Orgs, Environments, and the Instance Model",
    "series": "salesforce-architect",
    "lesson": 2,
    "excerpt": "Why every Salesforce org rents a slice of a shared platform: multi-tenancy, metadata-driven design, the instance model, and the sandbox environments that keep Dev/QA/UAT/Prod safe.",
    "date": "August 05, 2026",
    "author": "Adroit Consulting",
    "readTime": "8 min read",
    "tags": [
      "Learn",
      "Salesforce",
      "Architect",
      "Multi-Tenancy"
    ],
    "status": "published"
  },
  {
    "slug": "what-is-an-agent",
    "title": "Lesson 1: What an Agent Actually Is (LLMs vs Rules vs Workflows)",
    "series": "agentic-ai",
    "lesson": 1,
    "excerpt": "The definitions that matter for the whole 90-lesson track: what separates a rules system, an LLM workflow, and a true agent, plus how to tell which one you're actually building.",
    "date": "August 04, 2026",
    "author": "Adroit Consulting",
    "readTime": "9 min read",
    "tags": [
      "Learn",
      "AI",
      "Agentic",
      "Foundations"
    ],
    "status": "published"
  },
  {
    "slug": "day-02-f2-project-needs-requirements-assumptions-risks-const",
    "title": "OmniStudio F-2: Project Needs: Requirements, Assumptions, Risks, Constraints",
    "series": "omni-studio-cert",
    "lesson": 2,
    "excerpt": "Determine a project's needs by evaluating a customer's requirements, assumptions, risks, and constraints. Day 2 of the 46-requirement OmniStudio Developer exam prep.",
    "date": "August 04, 2026",
    "author": "Adroit Consulting",
    "readTime": "6 min read",
    "tags": [
      "OmniStudio",
      "OmniStudio Fundamentals"
    ],
    "status": "published"
  },
  {
    "slug": "what-salesforce-system-architect-does",
    "title": "Lesson 1: What a Salesforce System Architect Actually Does: Role, Cert Track, CTA Endgame",
    "series": "salesforce-architect",
    "lesson": 1,
    "excerpt": "The Salesforce architect arc in one lesson: what System vs Application vs Technical Architects actually do, the certification ladder, and the CTA endgame.",
    "date": "August 04, 2026",
    "author": "Adroit Consulting",
    "readTime": "8 min read",
    "tags": [
      "Learn",
      "Salesforce",
      "Architect",
      "Certifications"
    ],
    "status": "published"
  },
  {
    "slug": "day-01-f1-omnistudio-solution-and-industry-use-cases",
    "title": "OmniStudio F-1: OmniStudio Solution & Industry Use Cases",
    "series": "omni-studio-cert",
    "lesson": 1,
    "excerpt": "Describe the OmniStudio solution as it applies to common customer use case scenarios in different industries (telco, energy, healthcare, public sector, etc.). Day 1 of the 46-requirement OmniStudio Developer exam prep.",
    "date": "August 03, 2026",
    "author": "Adroit Consulting",
    "readTime": "6 min read",
    "tags": [
      "OmniStudio",
      "OmniStudio Fundamentals"
    ],
    "status": "published"
  }
];
