import { LearnLesson, LearningSeries } from "./types";

/**
 * GENERATED by scripts/build-learn.js — DO NOT HAND-EDIT.
 * Run `node scripts/build-learn.js` (or npm run prebuild) to regenerate.
 */

/** All series, sorted by newest lesson date DESC (ties → slug asc). Empty dirs included with lessons: []. */
export const learnSeries: LearningSeries[] = [
  {
    "slug": "agentic-ai",
    "name": "Agentic AI Implementation Path",
    "description": "From single-agent prototypes to multi-agent orchestration — a practitioner's curriculum for shipping agentic systems.",
    "gradient": "from-amber to-yellow-600",
    "lessons": [
      {
        "slug": "tokens-context-cost-engineering-agents",
        "title": "Lesson 5: Tokens, Context Windows, and Cost Engineering for Agent Workloads",
        "series": "agentic-ai",
        "lesson": 5,
        "excerpt": "Agents don't just use tokens — they burn them: roughly 4x a chat conversation, 15x for multi-agent. The four levers that control the bill — budgeting, compression, caching, and model routing — with the math worked out on a real 10-agent pipeline.",
        "date": "August 08, 2026",
        "author": "Adroit Consulting",
        "readTime": "9 min read",
        "tags": [
          "Learn",
          "AI",
          "Agentic",
          "Cost"
        ]
      },
      {
        "slug": "prompting-for-agents-system-prompts-few-shot",
        "title": "Lesson 4: Prompting for Agents — System Prompts, Few-Shot, and When Prompts Aren't Enough",
        "series": "agentic-ai",
        "lesson": 4,
        "excerpt": "In an agent, the prompt isn't a single message — it's the constitution the loop obeys on every iteration. The anatomy of a production system prompt, how few-shot examples actually work, and the escalation ladder for when words stop being enough.",
        "date": "August 07, 2026",
        "author": "Adroit Consulting",
        "readTime": "10 min read",
        "tags": [
          "Learn",
          "AI",
          "Agentic",
          "Prompting"
        ]
      },
      {
        "slug": "the-agent-loop-perceive-reason-act-observe",
        "title": "Lesson 3: The Agent Loop — Perceive, Reason, Act, Observe, and Where Your Code Lives",
        "series": "agentic-ai",
        "lesson": 3,
        "excerpt": "The one while loop that turns a language model into an agent: the five stages of the loop, the pseudocode that runs underneath every framework, and exactly which parts of it are your code versus the runtime's.",
        "date": "August 06, 2026",
        "author": "Adroit Consulting",
        "readTime": "9 min read",
        "tags": [
          "Learn",
          "AI",
          "Agentic",
          "Foundations"
        ]
      },
      {
        "slug": "how-llms-work-tokens-context-inference",
        "title": "Lesson 2: How LLMs Work for Implementers — Tokens, Context, Inference, Temperature",
        "series": "agentic-ai",
        "lesson": 2,
        "excerpt": "The four knobs that decide every LLM bill, latency budget, and reliability call: what tokens actually are, how the context window constrains agents, how inference really runs, and what temperature does and doesn't do.",
        "date": "August 05, 2026",
        "author": "Adroit Consulting",
        "readTime": "9 min read",
        "tags": [
          "Learn",
          "AI",
          "Agentic",
          "Foundations"
        ]
      },
      {
        "slug": "what-is-an-agent",
        "title": "Lesson 1: What an Agent Actually Is — LLMs vs Rules vs Workflows",
        "series": "agentic-ai",
        "lesson": 1,
        "excerpt": "The definitions that matter for the whole 90-lesson track: what separates a rules system, an LLM workflow, and a true agent — and how to tell which one you're actually building.",
        "date": "August 04, 2026",
        "author": "Adroit Consulting",
        "readTime": "9 min read",
        "tags": [
          "Learn",
          "AI",
          "Agentic",
          "Foundations"
        ]
      }
    ],
    "totalLessons": 5
  },
  {
    "slug": "omni-studio-cert",
    "name": "OmniStudio Developer Certification",
    "description": "A 46-requirement deep dive for the Salesforce Certified OmniStudio Developer exam — one official exam-guide requirement per day, with config walkthroughs, exam traps, and practice questions.",
    "group": "Salesforce Certifications",
    "gradient": "from-red to-rose-600",
    "lessons": [
      {
        "slug": "day-06-f-6-testing-versioning-cloning",
        "title": "OmniStudio F-6: Testing, Versioning & Cloning Components",
        "series": "omni-studio-cert",
        "lesson": 6,
        "excerpt": "Explain testing, versioning, cloning where applicable through OmniStudio components — save vs. publish, cloning workflows, version snapshots for deployment.",
        "date": "August 8, 2026",
        "author": "Adroit Consulting",
        "readTime": "10 min read",
        "tags": [
          "OmniStudio",
          "OmniStudio Fundamentals"
        ]
      },
      {
        "slug": "day-05-f5-implementation-toolchain-sfcli-vbt-migration",
        "title": "OmniStudio F-5: Implementation Toolchain: SFCLI, VBT, Migration",
        "series": "omni-studio-cert",
        "lesson": 5,
        "excerpt": "Describe the tools required to complete the end-to-end implementation process (SFCLI, VBT, Migration, etc.). — Day 5 of the 46-requirement OmniStudio Developer exam prep.",
        "date": "August 07, 2026",
        "author": "Adroit Consulting",
        "readTime": "6 min read",
        "tags": [
          "OmniStudio",
          "OmniStudio Fundamentals"
        ]
      },
      {
        "slug": "day-04-f4-licensing-permission-set-licenses-permission-sets",
        "title": "OmniStudio F-4: Licensing, Permission Set Licenses & Permission Sets",
        "series": "omni-studio-cert",
        "lesson": 4,
        "excerpt": "Explain OmniStudio license requirements, Permission Set licenses and Permission Sets. — Day 4 of the 46-requirement OmniStudio Developer exam prep.",
        "date": "August 06, 2026",
        "author": "Adroit Consulting",
        "readTime": "6 min read",
        "tags": [
          "OmniStudio",
          "OmniStudio Fundamentals"
        ]
      },
      {
        "slug": "day-03-f3-managed-package-vs-standard-runtime-upgrades",
        "title": "OmniStudio F-3: Managed Package vs Standard Runtime; Upgrades",
        "series": "omni-studio-cert",
        "lesson": 3,
        "excerpt": "Explain Managed Package Runtime vs. Standard Runtime, Automatic Upgrades, and Manual Intervention Upgrade. — Day 3 of the 46-requirement OmniStudio Developer exam prep.",
        "date": "August 05, 2026",
        "author": "Adroit Consulting",
        "readTime": "6 min read",
        "tags": [
          "OmniStudio",
          "OmniStudio Fundamentals"
        ]
      },
      {
        "slug": "day-02-f2-project-needs-requirements-assumptions-risks-const",
        "title": "OmniStudio F-2: Project Needs: Requirements, Assumptions, Risks, Constraints",
        "series": "omni-studio-cert",
        "lesson": 2,
        "excerpt": "Determine a project's needs by evaluating a customer's requirements, assumptions, risks, and constraints. — Day 2 of the 46-requirement OmniStudio Developer exam prep.",
        "date": "August 04, 2026",
        "author": "Adroit Consulting",
        "readTime": "6 min read",
        "tags": [
          "OmniStudio",
          "OmniStudio Fundamentals"
        ]
      },
      {
        "slug": "day-01-f1-omnistudio-solution-and-industry-use-cases",
        "title": "OmniStudio F-1: OmniStudio Solution & Industry Use Cases",
        "series": "omni-studio-cert",
        "lesson": 1,
        "excerpt": "Describe the OmniStudio solution as it applies to common customer use case scenarios in different industries (telco, energy, healthcare, public sector — Day 1 of the 46-requirement OmniStudio Developer exam prep.",
        "date": "August 03, 2026",
        "author": "Adroit Consulting",
        "readTime": "6 min read",
        "tags": [
          "OmniStudio",
          "OmniStudio Fundamentals"
        ]
      }
    ],
    "totalLessons": 6
  },
  {
    "slug": "salesforce-architect",
    "name": "Salesforce System Architect Primer",
    "description": "A 90-lesson deep dive into Flow design, Apex patterns, and platform architecture for teams scaling on Salesforce.",
    "group": "Salesforce Certifications",
    "gradient": "from-sky to-blue-600",
    "lessons": [
      {
        "slug": "systems-architecture-what-it-means-ai-patterns",
        "title": "Lesson 5: General Systems Architecture — What 'Architecture' Means and Why AI Systems Reuse the Same Patterns",
        "series": "salesforce-architect",
        "lesson": 5,
        "excerpt": "The foundational concepts of systems architecture — components, interfaces, and design principles — and why every AI agent pattern (sequential, parallel, hierarchical) is a remix of patterns engineers have known for decades.",
        "date": "August 08, 2026",
        "author": "Adroit Consulting",
        "readTime": "9 min read",
        "tags": [
          "Learn",
          "Architect",
          "Systems Architecture",
          "AI Patterns",
          "General"
        ]
      },
      {
        "slug": "integration-fundamentals-rest-soap-bulk-apis",
        "title": "Lesson 4: Integration Fundamentals — REST, SOAP, Bulk APIs, and Picking the Right One",
        "series": "salesforce-architect",
        "lesson": 4,
        "excerpt": "The System Architect's home turf: when to call Salesforce with REST, when to reach for SOAP, when to hand it a CSV via Bulk API 2.0 — and the request limits that make the choice matter.",
        "date": "August 07, 2026",
        "author": "Adroit Consulting",
        "readTime": "9 min read",
        "tags": [
          "Learn",
          "Salesforce",
          "Architect",
          "Integration"
        ]
      },
      {
        "slug": "core-building-blocks-objects-fields-relationships",
        "title": "Lesson 3: Core Building Blocks — Objects, Fields, Relationships, Record Types, and Formula vs Roll-Up",
        "series": "salesforce-architect",
        "lesson": 3,
        "excerpt": "The architect's canvas: standard and custom objects, field types, lookup vs master-detail relationships, record types for process variation, and when to compute with a formula field vs a roll-up summary.",
        "date": "August 06, 2026",
        "author": "Adroit Consulting",
        "readTime": "8 min read",
        "tags": [
          "Learn",
          "Salesforce",
          "Architect",
          "Data Model"
        ]
      },
      {
        "slug": "multi-tenant-platform-architecture",
        "title": "Lesson 2: Multi-Tenant Platform Architecture — Orgs, Environments, and the Instance Model",
        "series": "salesforce-architect",
        "lesson": 2,
        "excerpt": "Why every Salesforce org rents a slice of a shared platform: multi-tenancy, metadata-driven design, the instance model, and the sandbox environments that keep Dev/QA/UAT/Prod safe.",
        "date": "August 05, 2026",
        "author": "Adroit Consulting",
        "readTime": "8 min read",
        "tags": [
          "Learn",
          "Salesforce",
          "Architect",
          "Multi-Tenancy"
        ]
      },
      {
        "slug": "what-salesforce-system-architect-does",
        "title": "Lesson 1: What a Salesforce System Architect Actually Does — Role, Cert Track, CTA Endgame",
        "series": "salesforce-architect",
        "lesson": 1,
        "excerpt": "The Salesforce architect arc in one lesson: what System vs Application vs Technical Architects actually do, the certification ladder, and the CTA endgame.",
        "date": "August 04, 2026",
        "author": "Adroit Consulting",
        "readTime": "8 min read",
        "tags": [
          "Learn",
          "Salesforce",
          "Architect",
          "Certifications"
        ]
      }
    ],
    "totalLessons": 5
  }
];

/** Flat list of every lesson, NEWEST FIRST (for sitemap, nav, flat lookups). */
export const learnLessons: LearnLesson[] = [
  {
    "slug": "tokens-context-cost-engineering-agents",
    "title": "Lesson 5: Tokens, Context Windows, and Cost Engineering for Agent Workloads",
    "series": "agentic-ai",
    "lesson": 5,
    "excerpt": "Agents don't just use tokens — they burn them: roughly 4x a chat conversation, 15x for multi-agent. The four levers that control the bill — budgeting, compression, caching, and model routing — with the math worked out on a real 10-agent pipeline.",
    "date": "August 08, 2026",
    "author": "Adroit Consulting",
    "readTime": "9 min read",
    "tags": [
      "Learn",
      "AI",
      "Agentic",
      "Cost"
    ]
  },
  {
    "slug": "day-06-f-6-testing-versioning-cloning",
    "title": "OmniStudio F-6: Testing, Versioning & Cloning Components",
    "series": "omni-studio-cert",
    "lesson": 6,
    "excerpt": "Explain testing, versioning, cloning where applicable through OmniStudio components — save vs. publish, cloning workflows, version snapshots for deployment.",
    "date": "August 8, 2026",
    "author": "Adroit Consulting",
    "readTime": "10 min read",
    "tags": [
      "OmniStudio",
      "OmniStudio Fundamentals"
    ]
  },
  {
    "slug": "systems-architecture-what-it-means-ai-patterns",
    "title": "Lesson 5: General Systems Architecture — What 'Architecture' Means and Why AI Systems Reuse the Same Patterns",
    "series": "salesforce-architect",
    "lesson": 5,
    "excerpt": "The foundational concepts of systems architecture — components, interfaces, and design principles — and why every AI agent pattern (sequential, parallel, hierarchical) is a remix of patterns engineers have known for decades.",
    "date": "August 08, 2026",
    "author": "Adroit Consulting",
    "readTime": "9 min read",
    "tags": [
      "Learn",
      "Architect",
      "Systems Architecture",
      "AI Patterns",
      "General"
    ]
  },
  {
    "slug": "prompting-for-agents-system-prompts-few-shot",
    "title": "Lesson 4: Prompting for Agents — System Prompts, Few-Shot, and When Prompts Aren't Enough",
    "series": "agentic-ai",
    "lesson": 4,
    "excerpt": "In an agent, the prompt isn't a single message — it's the constitution the loop obeys on every iteration. The anatomy of a production system prompt, how few-shot examples actually work, and the escalation ladder for when words stop being enough.",
    "date": "August 07, 2026",
    "author": "Adroit Consulting",
    "readTime": "10 min read",
    "tags": [
      "Learn",
      "AI",
      "Agentic",
      "Prompting"
    ]
  },
  {
    "slug": "day-05-f5-implementation-toolchain-sfcli-vbt-migration",
    "title": "OmniStudio F-5: Implementation Toolchain: SFCLI, VBT, Migration",
    "series": "omni-studio-cert",
    "lesson": 5,
    "excerpt": "Describe the tools required to complete the end-to-end implementation process (SFCLI, VBT, Migration, etc.). — Day 5 of the 46-requirement OmniStudio Developer exam prep.",
    "date": "August 07, 2026",
    "author": "Adroit Consulting",
    "readTime": "6 min read",
    "tags": [
      "OmniStudio",
      "OmniStudio Fundamentals"
    ]
  },
  {
    "slug": "integration-fundamentals-rest-soap-bulk-apis",
    "title": "Lesson 4: Integration Fundamentals — REST, SOAP, Bulk APIs, and Picking the Right One",
    "series": "salesforce-architect",
    "lesson": 4,
    "excerpt": "The System Architect's home turf: when to call Salesforce with REST, when to reach for SOAP, when to hand it a CSV via Bulk API 2.0 — and the request limits that make the choice matter.",
    "date": "August 07, 2026",
    "author": "Adroit Consulting",
    "readTime": "9 min read",
    "tags": [
      "Learn",
      "Salesforce",
      "Architect",
      "Integration"
    ]
  },
  {
    "slug": "the-agent-loop-perceive-reason-act-observe",
    "title": "Lesson 3: The Agent Loop — Perceive, Reason, Act, Observe, and Where Your Code Lives",
    "series": "agentic-ai",
    "lesson": 3,
    "excerpt": "The one while loop that turns a language model into an agent: the five stages of the loop, the pseudocode that runs underneath every framework, and exactly which parts of it are your code versus the runtime's.",
    "date": "August 06, 2026",
    "author": "Adroit Consulting",
    "readTime": "9 min read",
    "tags": [
      "Learn",
      "AI",
      "Agentic",
      "Foundations"
    ]
  },
  {
    "slug": "day-04-f4-licensing-permission-set-licenses-permission-sets",
    "title": "OmniStudio F-4: Licensing, Permission Set Licenses & Permission Sets",
    "series": "omni-studio-cert",
    "lesson": 4,
    "excerpt": "Explain OmniStudio license requirements, Permission Set licenses and Permission Sets. — Day 4 of the 46-requirement OmniStudio Developer exam prep.",
    "date": "August 06, 2026",
    "author": "Adroit Consulting",
    "readTime": "6 min read",
    "tags": [
      "OmniStudio",
      "OmniStudio Fundamentals"
    ]
  },
  {
    "slug": "core-building-blocks-objects-fields-relationships",
    "title": "Lesson 3: Core Building Blocks — Objects, Fields, Relationships, Record Types, and Formula vs Roll-Up",
    "series": "salesforce-architect",
    "lesson": 3,
    "excerpt": "The architect's canvas: standard and custom objects, field types, lookup vs master-detail relationships, record types for process variation, and when to compute with a formula field vs a roll-up summary.",
    "date": "August 06, 2026",
    "author": "Adroit Consulting",
    "readTime": "8 min read",
    "tags": [
      "Learn",
      "Salesforce",
      "Architect",
      "Data Model"
    ]
  },
  {
    "slug": "how-llms-work-tokens-context-inference",
    "title": "Lesson 2: How LLMs Work for Implementers — Tokens, Context, Inference, Temperature",
    "series": "agentic-ai",
    "lesson": 2,
    "excerpt": "The four knobs that decide every LLM bill, latency budget, and reliability call: what tokens actually are, how the context window constrains agents, how inference really runs, and what temperature does and doesn't do.",
    "date": "August 05, 2026",
    "author": "Adroit Consulting",
    "readTime": "9 min read",
    "tags": [
      "Learn",
      "AI",
      "Agentic",
      "Foundations"
    ]
  },
  {
    "slug": "day-03-f3-managed-package-vs-standard-runtime-upgrades",
    "title": "OmniStudio F-3: Managed Package vs Standard Runtime; Upgrades",
    "series": "omni-studio-cert",
    "lesson": 3,
    "excerpt": "Explain Managed Package Runtime vs. Standard Runtime, Automatic Upgrades, and Manual Intervention Upgrade. — Day 3 of the 46-requirement OmniStudio Developer exam prep.",
    "date": "August 05, 2026",
    "author": "Adroit Consulting",
    "readTime": "6 min read",
    "tags": [
      "OmniStudio",
      "OmniStudio Fundamentals"
    ]
  },
  {
    "slug": "multi-tenant-platform-architecture",
    "title": "Lesson 2: Multi-Tenant Platform Architecture — Orgs, Environments, and the Instance Model",
    "series": "salesforce-architect",
    "lesson": 2,
    "excerpt": "Why every Salesforce org rents a slice of a shared platform: multi-tenancy, metadata-driven design, the instance model, and the sandbox environments that keep Dev/QA/UAT/Prod safe.",
    "date": "August 05, 2026",
    "author": "Adroit Consulting",
    "readTime": "8 min read",
    "tags": [
      "Learn",
      "Salesforce",
      "Architect",
      "Multi-Tenancy"
    ]
  },
  {
    "slug": "what-is-an-agent",
    "title": "Lesson 1: What an Agent Actually Is — LLMs vs Rules vs Workflows",
    "series": "agentic-ai",
    "lesson": 1,
    "excerpt": "The definitions that matter for the whole 90-lesson track: what separates a rules system, an LLM workflow, and a true agent — and how to tell which one you're actually building.",
    "date": "August 04, 2026",
    "author": "Adroit Consulting",
    "readTime": "9 min read",
    "tags": [
      "Learn",
      "AI",
      "Agentic",
      "Foundations"
    ]
  },
  {
    "slug": "day-02-f2-project-needs-requirements-assumptions-risks-const",
    "title": "OmniStudio F-2: Project Needs: Requirements, Assumptions, Risks, Constraints",
    "series": "omni-studio-cert",
    "lesson": 2,
    "excerpt": "Determine a project's needs by evaluating a customer's requirements, assumptions, risks, and constraints. — Day 2 of the 46-requirement OmniStudio Developer exam prep.",
    "date": "August 04, 2026",
    "author": "Adroit Consulting",
    "readTime": "6 min read",
    "tags": [
      "OmniStudio",
      "OmniStudio Fundamentals"
    ]
  },
  {
    "slug": "what-salesforce-system-architect-does",
    "title": "Lesson 1: What a Salesforce System Architect Actually Does — Role, Cert Track, CTA Endgame",
    "series": "salesforce-architect",
    "lesson": 1,
    "excerpt": "The Salesforce architect arc in one lesson: what System vs Application vs Technical Architects actually do, the certification ladder, and the CTA endgame.",
    "date": "August 04, 2026",
    "author": "Adroit Consulting",
    "readTime": "8 min read",
    "tags": [
      "Learn",
      "Salesforce",
      "Architect",
      "Certifications"
    ]
  },
  {
    "slug": "day-01-f1-omnistudio-solution-and-industry-use-cases",
    "title": "OmniStudio F-1: OmniStudio Solution & Industry Use Cases",
    "series": "omni-studio-cert",
    "lesson": 1,
    "excerpt": "Describe the OmniStudio solution as it applies to common customer use case scenarios in different industries (telco, energy, healthcare, public sector — Day 1 of the 46-requirement OmniStudio Developer exam prep.",
    "date": "August 03, 2026",
    "author": "Adroit Consulting",
    "readTime": "6 min read",
    "tags": [
      "OmniStudio",
      "OmniStudio Fundamentals"
    ]
  }
];
